export = [
  {
    nid: 1110278,
    title: 'Petugas media maut nahas motosikal',
    created: 1685887753,
    changed: 1685887753,
    sponsored: 0,
    premium: 0,
    url: 'https://www.bharian.com.my/berita/kes/2023/06/1110278/petugas-media-maut-nahas-motosikal',
    internal_url: '/berita/kes/2023/06/1110278/petugas-media-maut-nahas-motosikal',
    emotion: null,
    segment: null,
    sentiment: null,
    field_hide_related_articles: false,
    field_force_ads: [

    ],
    field_article_author: null,
    field_author_email: null,
    field_article_authors: [

    ],
    field_byline_prefix: null,
    field_article_topic: {
      tid: 8453,
      name: 'Kes',
    },
    field_tags: [
      {
        tid: 150644,
        name: 'xnstp',
      },
      {
        tid: 341923,
        name: 'jurukamera agensi berita cna maut kemalangan',
      },
    ],
    field_article_images: [
      {
        fid: '4776368',
        uid: '9',
        filename: 'zaiham_1685887744.jpg',
        uri: 'gs://images/articles/zaiham_1685887744.jpg',
        filemime: 'image/jpeg',
        filesize: '143627',
        status: '1',
        timestamp: '1685887745',
        uuid: '684c7e57-d99f-4763-b97d-51a163584358',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '759',
        url: 'https://assets.bharian.com.my/images/articles/zaiham_1685887744.jpg',
        caption: 'Motosikal terbabit kemalangan mengorbankan jurukamera agensi berita di Kilometer 43 Lebuhraya Kuala Lumpur-Karak di Bentong, Pahang. - Foto FB Polis Bentong ',
        gn4id: 'bh-43657954',
      },
    ],
    field_article_images_filtered: [
      {
        fid: '4776368',
        uid: '9',
        filename: 'zaiham_1685887744.jpg',
        uri: 'gs://images/articles/zaiham_1685887744.jpg',
        filemime: 'image/jpeg',
        filesize: '143627',
        status: '1',
        timestamp: '1685887745',
        uuid: '684c7e57-d99f-4763-b97d-51a163584358',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '759',
        url: 'https://assets.bharian.com.my/images/articles/zaiham_1685887744.jpg',
        caption: 'Motosikal terbabit kemalangan mengorbankan jurukamera agensi berita di Kilometer 43 Lebuhraya Kuala Lumpur-Karak di Bentong, Pahang. - Foto FB Polis Bentong ',
        gn4id: 'bh-43657954',
      },
    ],
    field_article_videos: null,
    field_image_listing_featured_v2: 'https://assets.bharian.com.my/images/articles/BH4MEDIAMAUT-O_BHfield_image_listing_featured_v2.var_1685887752.jpg',
    field_image_listing_v2: 'https://assets.bharian.com.my/images/articles/BH4MEDIAMAUT-O_BHfield_image_listing_v2.var_1685887751.jpg',
    field_image_portrait: 'https://assets.bharian.com.my/images/articles/BH4MEDIAMAUT-O_BHfield_image_portrait.var_1685887751.jpg',
    field_image_socialmedia: 'https://assets.bharian.com.my/images/articles/BH4MEDIAMAUT-O_BHfield_image_socialmedia.var_1685887750.jpg',
    field_image_first_sb_featured: 'https://assets.bharian.com.my/images/articles/BH4MEDIAMAUT-O_BHfield_image_first_sb_featured.var_1685887749.jpg',
    field_image_second_sb_featured: 'https://assets.bharian.com.my/images/articles/BH4MEDIAMAUT-O_BHfield_image_second_sb_featured.var_1685887748.jpg',
    field_image_listing_featured: 'https://assets.bharian.com.my/images/articles/BH4MEDIAMAUT-O_BHfield_image_listing_featured.var_1685887748.jpg',
    field_image_listing_th: 'https://assets.bharian.com.my/images/articles/BH4MEDIAMAUT-O_BHfield_image_listing_th.var_1685887747.jpg',
    field_image_three_wide_col: 'https://assets.bharian.com.my/images/articles/BH4MEDIAMAUT-O_BHfield_image_three_wide_col.var_1685887746.jpg',
    field_image_two_wide_col: null,
    field_image_mobile_th: null,
    field_article_lead: 'KUANTAN: Jurukamera agensi berita, Channel News Asia (CNA), Khairul Azman Zainuddin maut dalam nahas motosikal di Kilometer 43 Lebuhraya Kuala Lumpur-Karak di Bentong, hari ini.',
    body: '<p>KUANTAN: Jurukamera agensi berita, Channel News Asia (CNA), Khairul Azman Zainuddin maut dalam nahas motosikal di Kilometer 43 Lebuhraya Kuala Lumpur-Karak di Bentong, hari ini.</p><p>Ketua Polis Daerah Bentong, Superintendan Zaiham Mohd Kahar, berkata kejadian jam 12 tengah hari itu ketika Khairul Azman, 45, dalam perjalanan menuju Kuala Lumpur.</p><p>Katanya, mangsa disahkan meninggal dunia di tempat kejadian akibat parah di kepala. </p><p>"Motosikal mangsa dipercayai hilang kawalan lalu melanggar pembahagi jalan sebelum tercampak ke laluan bertentangan. Mangsa juga dilanggar sebuah motosikal di laluan itu ditunggang lelaki berusia 46 tahun yang tidak sempat mengelak," katanya dalam kenyataan, hari ini. </p><p>Penunggang dan pembonceng sebuah lagi motosikal cedera ringan dan dirawat di Hospital Bentong.</p><p>Beliau berkata, kemalangan itu sedang disiasat lanjut mengikut Seksyen 41 (1) Akta Pengangkutan Jalan 1987.</p><p>Polis meminta saksi kejadian tampil membantu siasatan dengan menghubungi Pusat Kawalan Daerah (DCC) Ibu Pejabat Polis Daerah Bentong di talian 09-2222 222. - BERNAMA </p><p> </p><p>© New Straits Times Press (M) Bhd</p>',
    body_with_inline: '<p>KUANTAN: Jurukamera agensi berita, Channel News Asia (CNA), Khairul Azman Zainuddin maut dalam nahas motosikal di Kilometer 43 Lebuhraya Kuala Lumpur-Karak di Bentong, hari ini.</p>\n<p>Ketua Polis Daerah Bentong, Superintendan Zaiham Mohd Kahar, berkata kejadian jam 12 tengah hari itu ketika Khairul Azman, 45, dalam perjalanan menuju Kuala Lumpur.</p>\n<p>Katanya, mangsa disahkan meninggal dunia di tempat kejadian akibat parah di kepala. </p>\n<p>"Motosikal mangsa dipercayai hilang kawalan lalu melanggar pembahagi jalan sebelum tercampak ke laluan bertentangan. Mangsa juga dilanggar sebuah motosikal di laluan itu ditunggang lelaki berusia 46 tahun yang tidak sempat mengelak," katanya dalam kenyataan, hari ini. </p>\n<p>Penunggang dan pembonceng sebuah lagi motosikal cedera ringan dan dirawat di Hospital Bentong.</p>\n<p>Beliau berkata, kemalangan itu sedang disiasat lanjut mengikut Seksyen 41 (1) Akta Pengangkutan Jalan 1987.</p>\n<p>Polis meminta saksi kejadian tampil membantu siasatan dengan menghubungi Pusat Kawalan Daerah (DCC) Ibu Pejabat Polis Daerah Bentong di talian 09-2222 222. - BERNAMA </p>\n\n',
    word_count: 141,
  },
  {
    nid: 1110276,
    title: 'Sharmendran, Thinaah dinobat Olahragawan, Olahragawati Selangor',
    created: 1685887637,
    changed: 1685887637,
    sponsored: 0,
    premium: 0,
    url: 'https://www.bharian.com.my/sukan/lain-lain/2023/06/1110276/sharmendran-thinaah-dinobat-olahragawan-olahragawati-selangor',
    internal_url: '/sukan/lain-lain/2023/06/1110276/sharmendran-thinaah-dinobat-olahragawan-olahragawati-selangor',
    emotion: null,
    segment: null,
    sentiment: null,
    field_hide_related_articles: false,
    field_force_ads: [

    ],
    field_article_author: {
      tid: 22039,
      name: 'Ruwaida Md Zain',
      email: null,
      photo: null,
      internal_url: '/authors/ruwaida-md-zain',
    },
    field_author_email: 'bhsukan@bh.com.my',
    field_article_authors: [
      {
        tid: 22039,
        name: 'Ruwaida Md Zain',
        email: null,
        photo: null,
        internal_url: '/authors/ruwaida-md-zain',
      },
    ],
    field_byline_prefix: 'Oleh',
    field_article_topic: {
      tid: 8459,
      name: 'Lain-lain (Sukan)',
    },
    field_tags: [
      {
        tid: 5302,
        name: 'SELANGOR',
      },
      {
        tid: 42857,
        name: 'Olahragawan',
      },
    ],
    field_article_images: [
      {
        fid: '4776357',
        uid: '9',
        filename: 'amir_1685887629.jpg',
        uri: 'gs://images/articles/amir_1685887629.jpg',
        filemime: 'image/jpeg',
        filesize: '83189',
        status: '1',
        timestamp: '1685887629',
        uuid: '463833a4-86cd-4476-afdf-de9e498b7bfb',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '666',
        url: 'https://assets.bharian.com.my/images/articles/amir_1685887629.jpg',
        caption: 'Menteri Besar Selangor Datuk Seri Amirudin Shari (dua, kiri) menyampaikan Anugerah Olahragawan kepada atlet Karate, R Sharmendran pada Majlis Anugerah Sukan Negeri Selangor 2021-2022 di Dewan Jubli Perak Sultan Abdul Aziz hari ini. Foto: BERNAMA ',
        gn4id: 'bh-43657904',
      },
    ],
    field_article_images_filtered: [
      {
        fid: '4776357',
        uid: '9',
        filename: 'amir_1685887629.jpg',
        uri: 'gs://images/articles/amir_1685887629.jpg',
        filemime: 'image/jpeg',
        filesize: '83189',
        status: '1',
        timestamp: '1685887629',
        uuid: '463833a4-86cd-4476-afdf-de9e498b7bfb',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '666',
        url: 'https://assets.bharian.com.my/images/articles/amir_1685887629.jpg',
        caption: 'Menteri Besar Selangor Datuk Seri Amirudin Shari (dua, kiri) menyampaikan Anugerah Olahragawan kepada atlet Karate, R Sharmendran pada Majlis Anugerah Sukan Negeri Selangor 2021-2022 di Dewan Jubli Perak Sultan Abdul Aziz hari ini. Foto: BERNAMA ',
        gn4id: 'bh-43657904',
      },
    ],
    field_article_videos: null,
    field_image_listing_featured_v2: 'https://assets.bharian.com.my/images/articles/olah_BHfield_image_listing_featured_v2.var_1685887637.jpg',
    field_image_listing_v2: 'https://assets.bharian.com.my/images/articles/olah_BHfield_image_listing_v2.var_1685887636.jpg',
    field_image_portrait: 'https://assets.bharian.com.my/images/articles/olah_BHfield_image_portrait.var_1685887635.jpg',
    field_image_socialmedia: 'https://assets.bharian.com.my/images/articles/olah_BHfield_image_socialmedia.var_1685887635.jpg',
    field_image_first_sb_featured: 'https://assets.bharian.com.my/images/articles/olah_BHfield_image_first_sb_featured.var_1685887634.jpg',
    field_image_second_sb_featured: 'https://assets.bharian.com.my/images/articles/olah_BHfield_image_second_sb_featured.var_1685887633.jpg',
    field_image_listing_featured: 'https://assets.bharian.com.my/images/articles/olah_BHfield_image_listing_featured.var_1685887632.jpg',
    field_image_listing_th: 'https://assets.bharian.com.my/images/articles/olah_BHfield_image_listing_th.var_1685887632.jpg',
    field_image_three_wide_col: 'https://assets.bharian.com.my/images/articles/olah_BHfield_image_three_wide_col.var_1685887631.jpg',
    field_image_two_wide_col: null,
    field_image_mobile_th: null,
    field_article_lead: 'SHAH ALAM: Atlet karate negara, R Sharmendran dan pemain badminton beregu wanita, M Thinaah dinobatkan sebagai Olahragawan dan Olahragawati Selangor bagi 2021-2022.',
    body: 'bhsukan@bh.com.my<p /><p>SHAH ALAM: Atlet karate negara, R Sharmendran dan pemain badminton beregu wanita, M Thinaah dinobatkan sebagai Olahragawan dan Olahragawati Selangor bagi 2021-2022.</p><p /><p>Kemenangan itu membolehkan masing-masing membawa pulang hadiah wang tunai RM10,000, piala iringan dan sijil dalam majlis Anugerah Sukan Negeri Selangor (ASNS) di Dewan Jubli Perak, Sultan Abdul Shah, di sini, hari ini.</p><p /><p>Menteri Besar, Datuk Seri Amirudin Shari berkata, penganjuran ASNS sebagai tanda penghargaan kerajaan negeri kepada individu serta kumpulan berkenaan di atas jasa perkhidmatan serta kepimpinan ke arah kemajuan sukan Selangor.</p><p /><p>"Ini tanda penghargaan kerajaan negeri kepada penggiat sukan yang mengharumkan negeri di peringkat kebangsaan dan antarabangsa. </p><p /><p>"Seramai 83 olahragawan dan olahragawati dianugerahkan sepanjang ASNS ini diadakan yang bermula dari tahun 1975 sehingga  tahun 2018," katanya dalam sidang media selepas menyempurnakan ASNS. </p><p /><p>Amirudin berkata, ASNS adalah pemangkin semangat kepada atlet baru untuk meningkatkan kualiti dan mengharumkan nama Selangor ke peringkat tertinggi. </p><p /><p>"Dengan majlis seperti ini, diharapkan akan mengeratkan hubungan antara penggiat sukan dengan wakil media dalam membantu menaikkan semangat atlet-atlet. </p><p /><p>"Majlis ini juga dapat mempertemukan atlet baru dan bekas atlet di samping dapat bertukar pendapat dan idea dalam mempertingkat kualiti diri dalam perkembangan sukan tanah air," katanya.</p><p /><p>Selain Sharmendran dan Thinaah katanya, ASNS turut meraikan Olahragawan dan Olahragawati Harapan yang dianugerahkan kepada perenang muda negara Andrew Goh Zheng Yen dan pemain tenis, Saw Jo-Leen.</p><p /><p>Mereka membawa pulang hadiah wang tunai RM10,000, piala iringan dan sijil penghargaan.</p><p>© New Straits Times Press (M) Bhd</p>',
    body_with_inline: '</p><p>SHAH ALAM: Atlet karate negara, R Sharmendran dan pemain badminton beregu wanita, M Thinaah dinobatkan sebagai Olahragawan dan Olahragawati Selangor bagi 2021-2022.</p>\n<p>Kemenangan itu membolehkan masing-masing membawa pulang hadiah wang tunai RM10,000, piala iringan dan sijil dalam majlis Anugerah Sukan Negeri Selangor (ASNS) di Dewan Jubli Perak, Sultan Abdul Shah, di sini, hari ini.</p>\n<p>Menteri Besar, Datuk Seri Amirudin Shari berkata, penganjuran ASNS sebagai tanda penghargaan kerajaan negeri kepada individu serta kumpulan berkenaan di atas jasa perkhidmatan serta kepimpinan ke arah kemajuan sukan Selangor.</p>\n<p>"Ini tanda penghargaan kerajaan negeri kepada penggiat sukan yang mengharumkan negeri di peringkat kebangsaan dan antarabangsa. </p>\n<p>"Seramai 83 olahragawan dan olahragawati dianugerahkan sepanjang ASNS ini diadakan yang bermula dari tahun 1975 sehingga  tahun 2018," katanya dalam sidang media selepas menyempurnakan ASNS. </p>\n<p>Amirudin berkata, ASNS adalah pemangkin semangat kepada atlet baru untuk meningkatkan kualiti dan mengharumkan nama Selangor ke peringkat tertinggi. </p>\n<p>"Dengan majlis seperti ini, diharapkan akan mengeratkan hubungan antara penggiat sukan dengan wakil media dalam membantu menaikkan semangat atlet-atlet. </p>\n<p>"Majlis ini juga dapat mempertemukan atlet baru dan bekas atlet di samping dapat bertukar pendapat dan idea dalam mempertingkat kualiti diri dalam perkembangan sukan tanah air," katanya.</p>\n<p>Selain Sharmendran dan Thinaah katanya, ASNS turut meraikan Olahragawan dan Olahragawati Harapan yang dianugerahkan kepada perenang muda negara Andrew Goh Zheng Yen dan pemain tenis, Saw Jo-Leen.</p>\n<p>Mereka membawa pulang hadiah wang tunai RM10,000, piala iringan dan sijil penghargaan.</p>\n',
    word_count: 229,
  },
  {
    nid: 1110274,
    title: 'Wanita tipu diculik, minta keluarga bayar wang tebusan RM100,000 dibebas dengan jaminan polis',
    created: 1685887556,
    changed: 1685887556,
    sponsored: 0,
    premium: 0,
    url: 'https://www.bharian.com.my/berita/kes/2023/06/1110274/wanita-tipu-diculik-minta-keluarga-bayar-wang-tebusan-rm100000-dibebas',
    internal_url: '/berita/kes/2023/06/1110274/wanita-tipu-diculik-minta-keluarga-bayar-wang-tebusan-rm100000-dibebas',
    emotion: null,
    segment: null,
    sentiment: null,
    field_hide_related_articles: false,
    field_force_ads: [

    ],
    field_article_author: {
      tid: 56660,
      name: 'Muhaamad Hafis Nawawi',
      email: null,
      photo: null,
      internal_url: '/authors/muhaamad-hafis-nawawi',
    },
    field_author_email: 'bhnews@bh.com.my',
    field_article_authors: [
      {
        tid: 56660,
        name: 'Muhaamad Hafis Nawawi',
        email: null,
        photo: null,
        internal_url: '/authors/muhaamad-hafis-nawawi',
      },
    ],
    field_byline_prefix: null,
    field_article_topic: {
      tid: 8453,
      name: 'Kes',
    },
    field_tags: [
      {
        tid: 8749,
        name: 'dibebaskan',
      },
      {
        tid: 341921,
        name: 'wanita tipu kena culik',
      },
      {
        tid: 341922,
        name: 'peras keluargar rm100000',
      },
    ],
    field_article_images: [
      {
        fid: '4776346',
        uid: '9',
        filename: 'bh4susulculik_1685887548.jpg',
        uri: 'gs://images/articles/bh4susulculik_1685887548.jpg',
        filemime: 'image/jpeg',
        filesize: '88987',
        status: '1',
        timestamp: '1685887548',
        uuid: 'ed61afa0-412b-4b20-985d-5574b8ec76d5',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '600',
        url: 'https://assets.bharian.com.my/images/articles/bh4susulculik_1685887548.jpg',
        caption: 'Laporan dalam BH Online mengenai wanita berusia 19 tahun yang mendakwa dirinya dilarikan orang dan memeras wang tebusan RM100,000 daripada keluarganya sendiri.',
        gn4id: 'bh-43657803',
      },
    ],
    field_article_images_filtered: [
      {
        fid: '4776346',
        uid: '9',
        filename: 'bh4susulculik_1685887548.jpg',
        uri: 'gs://images/articles/bh4susulculik_1685887548.jpg',
        filemime: 'image/jpeg',
        filesize: '88987',
        status: '1',
        timestamp: '1685887548',
        uuid: 'ed61afa0-412b-4b20-985d-5574b8ec76d5',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '600',
        url: 'https://assets.bharian.com.my/images/articles/bh4susulculik_1685887548.jpg',
        caption: 'Laporan dalam BH Online mengenai wanita berusia 19 tahun yang mendakwa dirinya dilarikan orang dan memeras wang tebusan RM100,000 daripada keluarganya sendiri.',
        gn4id: 'bh-43657803',
      },
    ],
    field_article_videos: null,
    field_image_listing_featured_v2: 'https://assets.bharian.com.my/images/articles/BH4SUSULCULIK-O_BHfield_image_listing_featured_v2.var_1685887555.jpg',
    field_image_listing_v2: 'https://assets.bharian.com.my/images/articles/BH4SUSULCULIK-O_BHfield_image_listing_v2.var_1685887555.jpg',
    field_image_portrait: 'https://assets.bharian.com.my/images/articles/BH4SUSULCULIK-O_BHfield_image_portrait.var_1685887554.jpg',
    field_image_socialmedia: 'https://assets.bharian.com.my/images/articles/BH4SUSULCULIK-O_BHfield_image_socialmedia.var_1685887554.jpg',
    field_image_first_sb_featured: 'https://assets.bharian.com.my/images/articles/BH4SUSULCULIK-O_BHfield_image_first_sb_featured.var_1685887552.jpg',
    field_image_second_sb_featured: 'https://assets.bharian.com.my/images/articles/BH4SUSULCULIK-O_BHfield_image_second_sb_featured.var_1685887552.jpg',
    field_image_listing_featured: 'https://assets.bharian.com.my/images/articles/BH4SUSULCULIK-O_BHfield_image_listing_featured.var_1685887551.jpg',
    field_image_listing_th: 'https://assets.bharian.com.my/images/articles/BH4SUSULCULIK-O_BHfield_image_listing_th.var_1685887551.jpg',
    field_image_three_wide_col: 'https://assets.bharian.com.my/images/articles/BH4SUSULCULIK-O_BHfield_image_three_wide_col.var_1685887550.jpg',
    field_image_two_wide_col: null,
    field_image_mobile_th: null,
    field_article_lead: 'AMPANG JAYA: Wanita berusia 19 tahun yang ditahan polis kerana mendakwa dirinya diculik sebelum memeras wang tebusan RM100,000 daripada keluarganya sendiri, hari ini dibebaskan dengan jaminan polis.',
    body: 'bhnews@bh.com.my<p /><p>AMPANG JAYA: Wanita berusia 19 tahun yang <a href="https://www.bharian.com.my/berita/kes/2023/06/1109756/wanita-reka-cerita-dilarikan-minta-keluarga-bayar-wang-tebusan-rm100000">ditahan polis</a> kerana mendakwa dirinya diculik sebelum memeras wang tebusan RM100,000 daripada keluarganya sendiri, hari ini dibebaskan dengan jaminan polis.</p><p /><p>Ketua Polis Daerah Ampang Jaya, Asisten Komisioner Mohamad Farouk Eshak, berkata kertas siasatan berhubung kejadian itu akan diserahkan kepada Pejabat Timbalan Pendakwa Raya pada Selasa ini untuk tindakan lanjut.</p><p /><p>Semalam, media melaporkan kejadian bermula ketika suspek keluar bersama keluarganya ke pusat beli-belah Ampang Point di sini, Khamis lalu.</p><p /><p>Pada jam 1.30 tengah hari, bapa suspek yang berusia 44 tahun dan bekerja sebagai perunding arkitek menyedari anaknya itu hilang selepas meminta izin untuk ke tandas.</p><p /><p>Kira-kira jam 3.30 petang, ibu suspek pula menerima mesej menerusi aplikasi WhatsApp dari nombor telefon anaknya itu, meminta RM100,000 konon untuk menyelamatkannya.</p><p /><p>Polis yang menerima laporan terus menjalankan siasatan sebelum sepasukan anggota dari Bahagian Siasatan Jenayah Ibu Pejabat Polis Daerah (IPD) Ampang Jaya menyerbu sebuah rumah di Taman Sri Muda, Shah Alam, Selangor pada jam 10 malam hari sama.</p><p /><p>Dalam serbuan ke rumah teman lelaki wanita terbabit, polis menahan suspek dan merampas telefon bimbit miliknya untuk siasatan.</p><p /><p>Hasil soal siasat, suspek mengaku mereka-reka cerita dan menaip sendiri mesej berkaitan wang tebusan RM100,000 berkenaan, manakala kejadian dia dilarikan orang itu sebenarnya tidak berlaku.</p><p /><p>Punca kejadian kerana suspek mendakwa dia sering dikongkong oleh ahli keluarga dan tidak mendapat kebebasan. Wanita berkenaan direman tiga hari untuk siasatan mengikut Seksyen 384 dan Seksyen 182 Kanun Keseksaan.</p><p /><p>Jika sabit kesalahan melakukan pemerasan dan memberi maklumat palsu, boleh dikenakan hukuman penjara sehingga enam bulan atau denda RM2,000 atau kedua-duanya sekali.</p><p>© New Straits Times Press (M) Bhd</p>',
    body_with_inline: '</p><p>AMPANG JAYA: Wanita berusia 19 tahun yang <a href="https://www.bharian.com.my/berita/kes/2023/06/1109756/wanita-reka-cerita-dilarikan-minta-keluarga-bayar-wang-tebusan-rm100000">ditahan polis</a> kerana mendakwa dirinya diculik sebelum memeras wang tebusan RM100,000 daripada keluarganya sendiri, hari ini dibebaskan dengan jaminan polis.</p>\n<p>Ketua Polis Daerah Ampang Jaya, Asisten Komisioner Mohamad Farouk Eshak, berkata kertas siasatan berhubung kejadian itu akan diserahkan kepada Pejabat Timbalan Pendakwa Raya pada Selasa ini untuk tindakan lanjut.</p>\n<p>Semalam, media melaporkan kejadian bermula ketika suspek keluar bersama keluarganya ke pusat beli-belah Ampang Point di sini, Khamis lalu.</p>\n<p>Pada jam 1.30 tengah hari, bapa suspek yang berusia 44 tahun dan bekerja sebagai perunding arkitek menyedari anaknya itu hilang selepas meminta izin untuk ke tandas.</p>\n<p>Kira-kira jam 3.30 petang, ibu suspek pula menerima mesej menerusi aplikasi WhatsApp dari nombor telefon anaknya itu, meminta RM100,000 konon untuk menyelamatkannya.</p>\n<p>Polis yang menerima laporan terus menjalankan siasatan sebelum sepasukan anggota dari Bahagian Siasatan Jenayah Ibu Pejabat Polis Daerah (IPD) Ampang Jaya menyerbu sebuah rumah di Taman Sri Muda, Shah Alam, Selangor pada jam 10 malam hari sama.</p>\n<p>Dalam serbuan ke rumah teman lelaki wanita terbabit, polis menahan suspek dan merampas telefon bimbit miliknya untuk siasatan.</p>\n<p>Hasil soal siasat, suspek mengaku mereka-reka cerita dan menaip sendiri mesej berkaitan wang tebusan RM100,000 berkenaan, manakala kejadian dia dilarikan orang itu sebenarnya tidak berlaku.</p>\n<p>Punca kejadian kerana suspek mendakwa dia sering dikongkong oleh ahli keluarga dan tidak mendapat kebebasan. Wanita berkenaan direman tiga hari untuk siasatan mengikut Seksyen 384 dan Seksyen 182 Kanun Keseksaan.</p>\n<p>Jika sabit kesalahan melakukan pemerasan dan memberi maklumat palsu, boleh dikenakan hukuman penjara sehingga enam bulan atau denda RM2,000 atau kedua-duanya sekali.</p>\n',
    word_count: 251,
  },
  {
    nid: 1110272,
    title: 'Polis tahan 2 lelaki, rampas 600 biji pil merah disyaki dadah',
    created: 1685886465,
    changed: 1685886465,
    sponsored: 0,
    premium: 0,
    url: 'https://www.bharian.com.my/berita/kes/2023/06/1110272/polis-tahan-2-lelaki-rampas-600-biji-pil-merah-disyaki-dadah',
    internal_url: '/berita/kes/2023/06/1110272/polis-tahan-2-lelaki-rampas-600-biji-pil-merah-disyaki-dadah',
    emotion: null,
    segment: null,
    sentiment: null,
    field_hide_related_articles: false,
    field_force_ads: [

    ],
    field_article_author: {
      tid: 104503,
      name: 'Hazira Ahmad Zaidi',
      email: null,
      photo: null,
      internal_url: '/authors/hazira-ahmad-zaidi',
    },
    field_author_email: 'bhnews@bh.com.my',
    field_article_authors: [
      {
        tid: 104503,
        name: 'Hazira Ahmad Zaidi',
        email: null,
        photo: null,
        internal_url: '/authors/hazira-ahmad-zaidi',
      },
    ],
    field_byline_prefix: null,
    field_article_topic: {
      tid: 8453,
      name: 'Kes',
    },
    field_tags: [
      {
        tid: 341919,
        name: 'polis tahan dua lelaki',
      },
      {
        tid: 341920,
        name: 'rampas 600 biji pil disyaki dadah',
      },
    ],
    field_article_images: [
      {
        fid: '4776334',
        uid: '9',
        filename: 'gari-hiasan_freepik_1685886455.jpg',
        uri: 'gs://images/articles/gari-hiasan_freepik_1685886455.jpg',
        filemime: 'image/jpeg',
        filesize: '318409',
        status: '1',
        timestamp: '1685886456',
        uuid: 'ffc0bb70-eccb-4aba-8162-a07177fcc99e',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '640',
        url: 'https://assets.bharian.com.my/images/articles/gari-hiasan_freepik_1685886455.jpg',
        caption: 'Foto hiasan.',
        gn4id: 'bh-35516272',
      },
      {
        fid: '4776335',
        uid: '9',
        filename: 'pils_1685886457.jpg',
        uri: 'gs://images/articles/pils_1685886457.jpg',
        filemime: 'image/jpeg',
        filesize: '105445',
        status: '1',
        timestamp: '1685886458',
        uuid: 'fcb3eabf-0a50-4246-bbba-ebb2bd161440',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '561',
        url: 'https://assets.bharian.com.my/images/articles/pils_1685886457.jpg',
        caption: 'Sebahagian pil yang dirampas dari dalam Proton Waja di tepi jalan Kuala Krai–Gua Musang, Kuala Krai. - FOTO IHSAN PDRM',
        gn4id: 'bh-43657687',
      },
    ],
    field_article_images_filtered: [
      {
        fid: '4776334',
        uid: '9',
        filename: 'gari-hiasan_freepik_1685886455.jpg',
        uri: 'gs://images/articles/gari-hiasan_freepik_1685886455.jpg',
        filemime: 'image/jpeg',
        filesize: '318409',
        status: '1',
        timestamp: '1685886456',
        uuid: 'ffc0bb70-eccb-4aba-8162-a07177fcc99e',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '640',
        url: 'https://assets.bharian.com.my/images/articles/gari-hiasan_freepik_1685886455.jpg',
        caption: 'Foto hiasan.',
        gn4id: 'bh-35516272',
      },
    ],
    field_article_videos: null,
    field_image_listing_featured_v2: 'https://assets.bharian.com.my/images/articles/BH4DADAHKRAI-O_BHfield_image_listing_featured_v2.var_1685886465.jpg',
    field_image_listing_v2: 'https://assets.bharian.com.my/images/articles/BH4DADAHKRAI-O_BHfield_image_listing_v2.var_1685886464.jpg',
    field_image_portrait: 'https://assets.bharian.com.my/images/articles/BH4DADAHKRAI-O_BHfield_image_portrait.var_1685886464.jpg',
    field_image_socialmedia: 'https://assets.bharian.com.my/images/articles/BH4DADAHKRAI-O_BHfield_image_socialmedia.var_1685886463.jpg',
    field_image_first_sb_featured: 'https://assets.bharian.com.my/images/articles/BH4DADAHKRAI-O_BHfield_image_first_sb_featured.var_1685886462.jpg',
    field_image_second_sb_featured: 'https://assets.bharian.com.my/images/articles/BH4DADAHKRAI-O_BHfield_image_second_sb_featured.var_1685886461.jpg',
    field_image_listing_featured: 'https://assets.bharian.com.my/images/articles/BH4DADAHKRAI-O_BHfield_image_listing_featured.var_1685886460.jpg',
    field_image_listing_th: 'https://assets.bharian.com.my/images/articles/BH4DADAHKRAI-O_BHfield_image_listing_th.var_1685886459.jpg',
    field_image_three_wide_col: 'https://assets.bharian.com.my/images/articles/BH4DADAHKRAI-O_BHfield_image_three_wide_col.var_1685886459.jpg',
    field_image_two_wide_col: null,
    field_image_mobile_th: null,
    field_article_lead: 'KUALA KRAI: Dua lelaki ditahan bersama 600 biji pil berwarna merah disyaki dadah dianggarkan bernilai RM6,000 dalam sebuah kereta Proton Waja, semalam.',
    body: 'bhnews@bh.com.my<p /><p>KUALA KRAI: Dua lelaki ditahan bersama 600 biji pil berwarna merah disyaki dadah dianggarkan bernilai RM6,000 dalam sebuah kereta Proton Waja, semalam.</p><p>Dalam kejadian kira-kira jam 10.20 malam itu, kedua-dua suspek ditahan anggota dari Balai Polis Kuala Krai di tepi jalan Kuala Krai-Gua Musang, di sini.</p><p>Timbalan Ketua Polis Daerah Kuala Krai, Deputi Superintendan Kamarulzaman Harun, berkata pemeriksaan ke atas kenderaan dinaiki suspek menemui tiga bungkusan plastik berisi 600 pil berwarna merah disyaki dadah dianggarkan bernilai RM6,000.</p><p /><p> </p><p /><p>"Ujian saringan air kencing ke atas kedua-dua suspek yang masing-masing berusia 26 tahun dan bekerja sebagai buruh serta penoreh getah itu mendapati mereka positif methamphetamine.</p><p>"Hasil semakan mendapati kedua-dua suspek tidak mempunyai rekod jenayah," katanya menerusi kenyataan, malam ini.</p><p>Beliau berkata, kedua-dua suspek direman tujuh hari bermula hari ini sehingga 10 Jun untuk siasatan mengikut Seksyen 39B dan Seksyen 15(1)(a) Akta Dadah Berbahaya (ADB) 1952.</p><p>Seksyen 39B memperuntukkan hukuman gantung sampai mati jika sabit kesalahan, manakala Seksyen 15(1)(a) memperuntukkan hukuman denda tidak melebihi RM5,000 atau penjara tidak kurang dua tahun.</p><p>"Polis turut merampas kereta Proton Waja yang dinaiki kedua-dua suspek," katanya.</p><p>© New Straits Times Press (M) Bhd</p>',
    body_with_inline: '</p><p>KUALA KRAI: Dua lelaki ditahan bersama 600 biji pil berwarna merah disyaki dadah dianggarkan bernilai RM6,000 dalam sebuah kereta Proton Waja, semalam.</p>\n<p>Dalam kejadian kira-kira jam 10.20 malam itu, kedua-dua suspek ditahan anggota dari Balai Polis Kuala Krai di tepi jalan Kuala Krai-Gua Musang, di sini.</p>\n<p>Timbalan Ketua Polis Daerah Kuala Krai, Deputi Superintendan Kamarulzaman Harun, berkata pemeriksaan ke atas kenderaan dinaiki suspek menemui tiga bungkusan plastik berisi 600 pil berwarna merah disyaki dadah dianggarkan bernilai RM6,000.</p>\n<p> <figure class="article-image-item gn4-inline-image inline-image image-single-single"><img class="img-responsive img-fluid lazyload" typeof="foaf:Image" data-src="https://assets.bharian.com.my/images/articles/pils_1685886457.jpg" alt="Sebahagian pil yang dirampas dari dalam Proton Waja di tepi jalan Kuala Krai–Gua Musang, Kuala Krai. - FOTO IHSAN PDRM" /><figcaption class="gn4-inline-image-caption">Sebahagian pil yang dirampas dari dalam Proton Waja di tepi jalan Kuala Krai–Gua Musang, Kuala Krai. - FOTO IHSAN PDRM</figcaption></figure></p>\n<p>"Ujian saringan air kencing ke atas kedua-dua suspek yang masing-masing berusia 26 tahun dan bekerja sebagai buruh serta penoreh getah itu mendapati mereka positif methamphetamine.</p>\n<p>"Hasil semakan mendapati kedua-dua suspek tidak mempunyai rekod jenayah," katanya menerusi kenyataan, malam ini.</p>\n<p>Beliau berkata, kedua-dua suspek direman tujuh hari bermula hari ini sehingga 10 Jun untuk siasatan mengikut Seksyen 39B dan Seksyen 15(1)(a) Akta Dadah Berbahaya (ADB) 1952.</p>\n<p>Seksyen 39B memperuntukkan hukuman gantung sampai mati jika sabit kesalahan, manakala Seksyen 15(1)(a) memperuntukkan hukuman denda tidak melebihi RM5,000 atau penjara tidak kurang dua tahun.</p>\n<p>"Polis turut merampas kereta Proton Waja yang dinaiki kedua-dua suspek," katanya.</p>\n',
    word_count: 177,
  },
  {
    nid: 1110269,
    title: 'Iraq, Syria bincang tangani perdagangan dadah rentas sempadan',
    created: 1685886206,
    changed: 1685886206,
    sponsored: 0,
    premium: 0,
    url: 'https://www.bharian.com.my/dunia/asia/2023/06/1110269/iraq-syria-bincang-tangani-perdagangan-dadah-rentas-sempadan',
    internal_url: '/dunia/asia/2023/06/1110269/iraq-syria-bincang-tangani-perdagangan-dadah-rentas-sempadan',
    emotion: null,
    segment: null,
    sentiment: null,
    field_hide_related_articles: false,
    field_force_ads: [

    ],
    field_article_author: null,
    field_author_email: null,
    field_article_authors: [

    ],
    field_byline_prefix: null,
    field_article_topic: {
      tid: 8460,
      name: 'Asia',
    },
    field_tags: null,
    field_article_images: [
      {
        fid: '4776323',
        uid: '9',
        filename: 'bhdas_1685886198.jpg',
        uri: 'gs://images/articles/bhdas_1685886198.jpg',
        filemime: 'image/jpeg',
        filesize: '104585',
        status: '1',
        timestamp: '1685886199',
        uuid: 'f03b3045-2899-43af-9e74-598f4a8a2a76',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '640',
        url: 'https://assets.bharian.com.my/images/articles/bhdas_1685886198.jpg',
        caption: 'Fuad (kanan) dan Faisal ketika sidang media di Baghdad. - AFP',
        gn4id: 'bh-43657608',
      },
    ],
    field_article_images_filtered: [
      {
        fid: '4776323',
        uid: '9',
        filename: 'bhdas_1685886198.jpg',
        uri: 'gs://images/articles/bhdas_1685886198.jpg',
        filemime: 'image/jpeg',
        filesize: '104585',
        status: '1',
        timestamp: '1685886199',
        uuid: 'f03b3045-2899-43af-9e74-598f4a8a2a76',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '640',
        url: 'https://assets.bharian.com.my/images/articles/bhdas_1685886198.jpg',
        caption: 'Fuad (kanan) dan Faisal ketika sidang media di Baghdad. - AFP',
        gn4id: 'bh-43657608',
      },
    ],
    field_article_videos: null,
    field_image_listing_featured_v2: 'https://assets.bharian.com.my/images/articles/BHIRAP_BHfield_image_listing_featured_v2.var_1685886206.jpg',
    field_image_listing_v2: 'https://assets.bharian.com.my/images/articles/BHIRAP_BHfield_image_listing_v2.var_1685886205.jpg',
    field_image_portrait: 'https://assets.bharian.com.my/images/articles/BHIRAP_BHfield_image_portrait.var_1685886204.jpg',
    field_image_socialmedia: 'https://assets.bharian.com.my/images/articles/BHIRAP_BHfield_image_socialmedia.var_1685886204.jpg',
    field_image_first_sb_featured: 'https://assets.bharian.com.my/images/articles/BHIRAP_BHfield_image_first_sb_featured.var_1685886203.jpg',
    field_image_second_sb_featured: 'https://assets.bharian.com.my/images/articles/BHIRAP_BHfield_image_second_sb_featured.var_1685886202.jpg',
    field_image_listing_featured: 'https://assets.bharian.com.my/images/articles/BHIRAP_BHfield_image_listing_featured.var_1685886201.jpg',
    field_image_listing_th: 'https://assets.bharian.com.my/images/articles/BHIRAP_BHfield_image_listing_th.var_1685886201.jpg',
    field_image_three_wide_col: 'https://assets.bharian.com.my/images/articles/BHIRAP_BHfield_image_three_wide_col.var_1685886200.jpg',
    field_image_two_wide_col: null,
    field_image_mobile_th: null,
    field_article_lead: 'BAGHDAD: Menteri Luar Iraq dan Syria membincangkan kaedah untuk membantu menamatkan pengedaran dadah rentas sempadan membabitkan kedua-dua negara.',
    body: "<p>BAGHDAD: Menteri Luar Iraq dan Syria membincangkan kaedah untuk membantu menamatkan pengedaran dadah rentas sempadan membabitkan kedua-dua negara.</p><p>   Menteri Luar Iraq, Fuad Hussein berkata mesyuarat kedua-dua pihak itu berlangsung di Baghdad hari ini.</p><p>   \"Hari ini kita membincangkan kerjasama antara Iraq dan Syria untuk memerangi perdagangan dadah. </p><p>  \"Sebagaimana diketahui, Iraq adalah koridor untuk pengedaran dan malangnya penggunaan dadah sudah bermula dalam kalangan masyarakat Iraq,\" katanya pada sidang media bersama Menteri Luar Syria, Faisal Mekdad.</p><p>  Faisal tiba di Baghdad petang semalam untuk rangka lawatan selama dua hari.</p><p>  Hussein berkata, krisis kemanusiaan pelarian Syria di Iraq yang dianggarkan mencecah 250,000 orang menjadi sebahagian daripada agenda rundingan dua hala itu.</p><p>  Presiden Syria, Bashar al-Assad, menerima sambutan hangat pada sidang kemuncak Liga Arab bulan lalu selepas negara-negara Arab bersetuju untuk mengembalikan keahlian penuh Syria dalam liga itu.</p><p>  Syria sebelum ini digantung selama 12 tahun berikutan tindakan keras terhadap peserta protes jalanan ke atas Assad yang membawa kepada perang saudara yang dahsyat.</p><p>  Setelah mengalu-alukan kembali penyertaan Assad, negara-negara Arab mahu pemimpin itu membendung perdagangan narkotik Syria yang berkembang pesat. </p><p>  Ia dihasilkan di Syria dan diseludup ke seluruh wilayah.</p><p>  Kerajaan Syria menafikan sebarang peranan dalam perdagangan itu, yang mana pegawai Syria dan saudara Assad berdepan sekatan Barat.</p><p>  Kerajaan Arab dan Barat menuduh Damsyik menghasilkan 'amphetamine captagon' yang menyebabkan ketagihan melampau dan menguntungkan, selain turut mengatur penyeludupannya ke negara Teluk.</p><p>  Menteri Luar Iraq dan Syria turut membincangkan langkah yang telah dicapai Syria di lapangan untuk mengekang perdagangan haram itu, kata seorang pegawai kerajaan Iraq yang menghadiri mesyuarat hari ini yang enggan identitinya didedahkan, kepada REUTERS.</p><p>  Menurut Hussein, ketika lawatannya ke Baghdad, Mekdad juga akan bertemu Presiden Iraq, Perdana Menteri, Speaker Parlimen dan Ketua Majlis Kehakiman Tertinggi. - REUTERS</p><p>© New Straits Times Press (M) Bhd</p>",
    body_with_inline: "<p>BAGHDAD: Menteri Luar Iraq dan Syria membincangkan kaedah untuk membantu menamatkan pengedaran dadah rentas sempadan membabitkan kedua-dua negara.</p>\n<p>   Menteri Luar Iraq, Fuad Hussein berkata mesyuarat kedua-dua pihak itu berlangsung di Baghdad hari ini.</p>\n<p>   \"Hari ini kita membincangkan kerjasama antara Iraq dan Syria untuk memerangi perdagangan dadah. </p>\n<p>  \"Sebagaimana diketahui, Iraq adalah koridor untuk pengedaran dan malangnya penggunaan dadah sudah bermula dalam kalangan masyarakat Iraq,\" katanya pada sidang media bersama Menteri Luar Syria, Faisal Mekdad.</p>\n<p>  Faisal tiba di Baghdad petang semalam untuk rangka lawatan selama dua hari.</p>\n<p>  Hussein berkata, krisis kemanusiaan pelarian Syria di Iraq yang dianggarkan mencecah 250,000 orang menjadi sebahagian daripada agenda rundingan dua hala itu.</p>\n<p>  Presiden Syria, Bashar al-Assad, menerima sambutan hangat pada sidang kemuncak Liga Arab bulan lalu selepas negara-negara Arab bersetuju untuk mengembalikan keahlian penuh Syria dalam liga itu.</p>\n<p>  Syria sebelum ini digantung selama 12 tahun berikutan tindakan keras terhadap peserta protes jalanan ke atas Assad yang membawa kepada perang saudara yang dahsyat.</p>\n<p>  Setelah mengalu-alukan kembali penyertaan Assad, negara-negara Arab mahu pemimpin itu membendung perdagangan narkotik Syria yang berkembang pesat. </p>\n<p>  Ia dihasilkan di Syria dan diseludup ke seluruh wilayah.</p>\n<p>  Kerajaan Syria menafikan sebarang peranan dalam perdagangan itu, yang mana pegawai Syria dan saudara Assad berdepan sekatan Barat.</p>\n<p>  Kerajaan Arab dan Barat menuduh Damsyik menghasilkan 'amphetamine captagon' yang menyebabkan ketagihan melampau dan menguntungkan, selain turut mengatur penyeludupannya ke negara Teluk.</p>\n<p>  Menteri Luar Iraq dan Syria turut membincangkan langkah yang telah dicapai Syria di lapangan untuk mengekang perdagangan haram itu, kata seorang pegawai kerajaan Iraq yang menghadiri mesyuarat hari ini yang enggan identitinya didedahkan, kepada REUTERS.</p>\n<p>  Menurut Hussein, ketika lawatannya ke Baghdad, Mekdad juga akan bertemu Presiden Iraq, Perdana Menteri, Speaker Parlimen dan Ketua Majlis Kehakiman Tertinggi. - REUTERS</p>\n",
    word_count: 278,
  },
  {
    nid: 1110267,
    title: 'R Sharmendran, M Thinaah olahragawan, olahragawati Selangor',
    created: 1685886097,
    changed: 1685886097,
    sponsored: 0,
    premium: 0,
    url: 'https://www.bharian.com.my/berita/nasional/2023/06/1110267/r-sharmendran-m-thinaah-olahragawan-olahragawati-selangor',
    internal_url: '/berita/nasional/2023/06/1110267/r-sharmendran-m-thinaah-olahragawan-olahragawati-selangor',
    emotion: null,
    segment: null,
    sentiment: null,
    field_hide_related_articles: false,
    field_force_ads: [

    ],
    field_article_author: {
      tid: 22039,
      name: 'Ruwaida Md Zain',
      email: null,
      photo: null,
      internal_url: '/authors/ruwaida-md-zain',
    },
    field_author_email: 'bhnews@bh.com.my',
    field_article_authors: [
      {
        tid: 22039,
        name: 'Ruwaida Md Zain',
        email: null,
        photo: null,
        internal_url: '/authors/ruwaida-md-zain',
      },
    ],
    field_byline_prefix: 'Oleh',
    field_article_topic: {
      tid: 1,
      name: 'Nasional',
    },
    field_tags: [
      {
        tid: 42857,
        name: 'Olahragawan',
      },
      {
        tid: 30369,
        name: 'olahragawati',
      },
      {
        tid: 1479,
        name: 'nasional',
      },
      {
        tid: 74810,
        name: 'Amirudin',
      },
    ],
    field_article_images: [
      {
        fid: '4776312',
        uid: '9',
        filename: 'anugerah_1685886088.jpg',
        uri: 'gs://images/articles/anugerah_1685886088.jpg',
        filemime: 'image/jpeg',
        filesize: '148469',
        status: '1',
        timestamp: '1685886089',
        uuid: 'c498c16d-7a00-4a27-a6dd-eeb3a58515b7',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '568',
        url: 'https://assets.bharian.com.my/images/articles/anugerah_1685886088.jpg',
        caption: 'Menteri Besar Selangor Datuk Seri Amirudin Shari (tengah) bergambar bersama pemenang anugerah sukan pada Majlis Anugerah Sukan Negeri Selangor 2021-2022 di Dewan Jubli Perak Sultan Abdul Aziz hari ini - Foto BERNAMA ',
        gn4id: 'bh-43657544',
      },
    ],
    field_article_images_filtered: [
      {
        fid: '4776312',
        uid: '9',
        filename: 'anugerah_1685886088.jpg',
        uri: 'gs://images/articles/anugerah_1685886088.jpg',
        filemime: 'image/jpeg',
        filesize: '148469',
        status: '1',
        timestamp: '1685886089',
        uuid: 'c498c16d-7a00-4a27-a6dd-eeb3a58515b7',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '568',
        url: 'https://assets.bharian.com.my/images/articles/anugerah_1685886088.jpg',
        caption: 'Menteri Besar Selangor Datuk Seri Amirudin Shari (tengah) bergambar bersama pemenang anugerah sukan pada Majlis Anugerah Sukan Negeri Selangor 2021-2022 di Dewan Jubli Perak Sultan Abdul Aziz hari ini - Foto BERNAMA ',
        gn4id: 'bh-43657544',
      },
    ],
    field_article_videos: null,
    field_image_listing_featured_v2: 'https://assets.bharian.com.my/images/articles/BH4OLAH-O_BHfield_image_listing_featured_v2.var_1685886096.jpg',
    field_image_listing_v2: 'https://assets.bharian.com.my/images/articles/BH4OLAH-O_BHfield_image_listing_v2.var_1685886095.jpg',
    field_image_portrait: 'https://assets.bharian.com.my/images/articles/BH4OLAH-O_BHfield_image_portrait.var_1685886095.jpg',
    field_image_socialmedia: 'https://assets.bharian.com.my/images/articles/BH4OLAH-O_BHfield_image_socialmedia.var_1685886094.jpg',
    field_image_first_sb_featured: 'https://assets.bharian.com.my/images/articles/BH4OLAH-O_BHfield_image_first_sb_featured.var_1685886093.jpg',
    field_image_second_sb_featured: 'https://assets.bharian.com.my/images/articles/BH4OLAH-O_BHfield_image_second_sb_featured.var_1685886092.jpg',
    field_image_listing_featured: 'https://assets.bharian.com.my/images/articles/BH4OLAH-O_BHfield_image_listing_featured.var_1685886092.jpg',
    field_image_listing_th: 'https://assets.bharian.com.my/images/articles/BH4OLAH-O_BHfield_image_listing_th.var_1685886091.jpg',
    field_image_three_wide_col: 'https://assets.bharian.com.my/images/articles/BH4OLAH-O_BHfield_image_three_wide_col.var_1685886090.jpg',
    field_image_two_wide_col: null,
    field_image_mobile_th: null,
    field_article_lead: 'SHAH ALAM: Selangor menobatkan atlet karate-do negara, R Sharmendran dan atlet badminton beregu wanita utama, M Thinaah sebagai Olahragawan dan Olahragawati Selangor bagi 2021-2022.',
    body: 'bhnews@bh.com.my<p /><p>SHAH ALAM: Selangor menobatkan atlet karate-do negara, R Sharmendran dan atlet badminton beregu wanita utama, M Thinaah sebagai Olahragawan dan Olahragawati Selangor bagi 2021-2022.</p><p>Dengan kemenangan itu, masing-masing  membawa pulang dengan hadiah wang tunai RM10,000, piala iringan dan sijil dalam majlis Anugerah Sukan Negeri Selangor (ASNS) di sini hari ini.</p><p>Menteri Besar, Datuk Seri Amirudin Shari berkata, penganjuran ASNS sebagai tanda penghargaan kerajaan negeri kepada individu serta kumpulan berkenaan di atas jasa perkhidmatan serta kepimpinan ke arah kemajuan sukan Selangor.</p><p>"Seramai 83 olahragawan dan olahragawati dianugerahkan sepanjang ASNS ini diadakan yang bermula dari tahun 1975 sehingga  tahun 2018," katanya dalam sidang media selepas menyempurnakan Majlis Anugerah Sukan Negeri Selangor di Dewan Jubli Perak, SUK di sini petang tadi. </p><p>Selain Sharmendran dan Thinaah katanya, ASNS turut meraikan Olahragawan dan Olahragawati Harapan yang dianugerahkan kepada perenang muda negara Andrew Goh Zheng Yen dan pemain tenis negara, Saw Jo-Leen.</p><p>"Masing-masing membawa pulang hadiah wang tunai RM10,000, piala iringan dan sijil penghargaan.</p><p>"Beberapa individu yang menyumbang kepada sukan turut menerima Anugerah Tokoh Kepimpinan Sukan, Anugerah Jurulatih Terbaik, Anugerah Juri serta Anugerah Pasukan Terbaik," katanya.</p><p /><p>© New Straits Times Press (M) Bhd</p>',
    body_with_inline: '</p><p>SHAH ALAM: Selangor menobatkan atlet karate-do negara, R Sharmendran dan atlet badminton beregu wanita utama, M Thinaah sebagai Olahragawan dan Olahragawati Selangor bagi 2021-2022.</p>\n<p>Dengan kemenangan itu, masing-masing  membawa pulang dengan hadiah wang tunai RM10,000, piala iringan dan sijil dalam majlis Anugerah Sukan Negeri Selangor (ASNS) di sini hari ini.</p>\n<p>Menteri Besar, Datuk Seri Amirudin Shari berkata, penganjuran ASNS sebagai tanda penghargaan kerajaan negeri kepada individu serta kumpulan berkenaan di atas jasa perkhidmatan serta kepimpinan ke arah kemajuan sukan Selangor.</p>\n<p>"Seramai 83 olahragawan dan olahragawati dianugerahkan sepanjang ASNS ini diadakan yang bermula dari tahun 1975 sehingga  tahun 2018," katanya dalam sidang media selepas menyempurnakan Majlis Anugerah Sukan Negeri Selangor di Dewan Jubli Perak, SUK di sini petang tadi. </p>\n<p>Selain Sharmendran dan Thinaah katanya, ASNS turut meraikan Olahragawan dan Olahragawati Harapan yang dianugerahkan kepada perenang muda negara Andrew Goh Zheng Yen dan pemain tenis negara, Saw Jo-Leen.</p>\n<p>"Masing-masing membawa pulang hadiah wang tunai RM10,000, piala iringan dan sijil penghargaan.</p>\n<p>"Beberapa individu yang menyumbang kepada sukan turut menerima Anugerah Tokoh Kepimpinan Sukan, Anugerah Jurulatih Terbaik, Anugerah Juri serta Anugerah Pasukan Terbaik," katanya.</p>\n',
    word_count: 180,
  },
  {
    nid: 1110265,
    title: 'Malaysia perkukuh kerjasama pertahanan melalui Dialog Shangri-La 2023',
    created: 1685885944,
    changed: 1685885944,
    sponsored: 0,
    premium: 0,
    url: 'https://www.bharian.com.my/berita/nasional/2023/06/1110265/malaysia-perkukuh-kerjasama-pertahanan-melalui-dialog-shangri-la',
    internal_url: '/berita/nasional/2023/06/1110265/malaysia-perkukuh-kerjasama-pertahanan-melalui-dialog-shangri-la',
    emotion: null,
    segment: null,
    sentiment: null,
    field_hide_related_articles: false,
    field_force_ads: [

    ],
    field_article_author: null,
    field_author_email: null,
    field_article_authors: [

    ],
    field_byline_prefix: null,
    field_article_topic: {
      tid: 1,
      name: 'Nasional',
    },
    field_tags: [
      {
        tid: 150644,
        name: 'xnstp',
      },
      {
        tid: 341918,
        name: 'malaysia perkukuh kerjasama pertahanan melalui dialog shangri-la',
      },
    ],
    field_article_images: [
      {
        fid: '4776301',
        uid: '9',
        filename: 'mathasanshang_1685885934.jpg',
        uri: 'gs://images/articles/mathasanshang_1685885934.jpg',
        filemime: 'image/jpeg',
        filesize: '101150',
        status: '1',
        timestamp: '1685885934',
        uuid: 'b26e7514-d7a9-4eab-b9df-5413e87f4d1d',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '638',
        url: 'https://assets.bharian.com.my/images/articles/mathasanshang_1685885934.jpg',
        caption: 'Datuk Seri Mohamad Hasan (empat dari kanan) bersama menteri-menteri pertahanan dan pegawai-pegawai tinggi kerajaan dari Asia Pasifik dan Eropah yang hadir forum Dialog Shangri-La 2023 (SLD2023) di Singapura. - Foto FB',
        gn4id: 'bh-43657517',
      },
    ],
    field_article_images_filtered: [
      {
        fid: '4776301',
        uid: '9',
        filename: 'mathasanshang_1685885934.jpg',
        uri: 'gs://images/articles/mathasanshang_1685885934.jpg',
        filemime: 'image/jpeg',
        filesize: '101150',
        status: '1',
        timestamp: '1685885934',
        uuid: 'b26e7514-d7a9-4eab-b9df-5413e87f4d1d',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '638',
        url: 'https://assets.bharian.com.my/images/articles/mathasanshang_1685885934.jpg',
        caption: 'Datuk Seri Mohamad Hasan (empat dari kanan) bersama menteri-menteri pertahanan dan pegawai-pegawai tinggi kerajaan dari Asia Pasifik dan Eropah yang hadir forum Dialog Shangri-La 2023 (SLD2023) di Singapura. - Foto FB',
        gn4id: 'bh-43657517',
      },
    ],
    field_article_videos: null,
    field_image_listing_featured_v2: 'https://assets.bharian.com.my/images/articles/BH4DIALOGSHANGRILA-O_BHfield_image_listing_featured_v2.var_1685885943.jpg',
    field_image_listing_v2: 'https://assets.bharian.com.my/images/articles/BH4DIALOGSHANGRILA-O_BHfield_image_listing_v2.var_1685885942.jpg',
    field_image_portrait: 'https://assets.bharian.com.my/images/articles/BH4DIALOGSHANGRILA-O_BHfield_image_portrait.var_1685885941.jpg',
    field_image_socialmedia: 'https://assets.bharian.com.my/images/articles/BH4DIALOGSHANGRILA-O_BHfield_image_socialmedia.var_1685885941.jpg',
    field_image_first_sb_featured: 'https://assets.bharian.com.my/images/articles/BH4DIALOGSHANGRILA-O_BHfield_image_first_sb_featured.var_1685885940.jpg',
    field_image_second_sb_featured: 'https://assets.bharian.com.my/images/articles/BH4DIALOGSHANGRILA-O_BHfield_image_second_sb_featured.var_1685885939.jpg',
    field_image_listing_featured: 'https://assets.bharian.com.my/images/articles/BH4DIALOGSHANGRILA-O_BHfield_image_listing_featured.var_1685885938.jpg',
    field_image_listing_th: 'https://assets.bharian.com.my/images/articles/BH4DIALOGSHANGRILA-O_BHfield_image_listing_th.var_1685885938.jpg',
    field_image_three_wide_col: 'https://assets.bharian.com.my/images/articles/BH4DIALOGSHANGRILA-O_BHfield_image_three_wide_col.var_1685885937.jpg',
    field_image_two_wide_col: null,
    field_image_mobile_th: null,
    field_article_lead: 'KUALA LUMPUR: Kesungguhan Malaysia dalam meningkatkan kerjasama pertahanan dengan negara serantau dan luar rantau dapat dilihat menerusi kehadiran Menteri Pertahanan, Datuk Seri Mohamad Hasan pada forum Dialog Shangri-La 2023 (SLD2023) di Singapura.',
    body: '<p>KUALA LUMPUR: Kesungguhan Malaysia dalam meningkatkan kerjasama pertahanan dengan negara serantau dan luar rantau dapat dilihat menerusi kehadiran Menteri Pertahanan, Datuk Seri Mohamad Hasan pada forum Dialog Shangri-La 2023 (SLD2023) di Singapura.</p><p>Kementerian Pertahanan dalam kenyataan memaklumkan, perkara itu selaras dengan tonggak ketiga strategi pertahanan negara yang menekankan perkongsian berwibawa seperti digariskan dalam Kertas Putih Pertahanan.</p><p>Kenyataan itu memaklumkan, forum dari 2 hingga 4 Jun itu memberi impak besar kepada Malaysia sebagai peneraju dalam isu pertahanan dan keselamatan di Asia Tenggara untuk bertukar-tukar pandangan serta mendengar pendirian negara lain berhubung isu keselamatan terkini.</p><p>"Di samping itu, forum berkenaan memperkukuh hubungan pertahanan dengan negara-negara berkepentingan," menurut kenyataan itu.</p><p>SLD2023 ialah forum keselamatan bertaraf antarabangsa melibatkan penyertaan menteri-menteri pertahanan dan pegawai-pegawai tinggi kerajaan dari negara di rantau Asia Pasifik dan benua Eropah.</p><p>Semasa forum tiga hari itu, Mohamad turut mengadakan pertemuan dua hala dan pelbagai hala bersama rakan sejawat dari negara strategik, antaranya Singapura, Portugal, China serta Filipina.</p><p>Selain itu, beliau menghadiri sesi mesyuarat bersama menteri pertahanan negara anggota Perjanjian Pertahanan Lima Negara (FPDA). - BERNAMA</p><p> </p><p>© New Straits Times Press (M) Bhd</p>',
    body_with_inline: '<p>KUALA LUMPUR: Kesungguhan Malaysia dalam meningkatkan kerjasama pertahanan dengan negara serantau dan luar rantau dapat dilihat menerusi kehadiran Menteri Pertahanan, Datuk Seri Mohamad Hasan pada forum Dialog Shangri-La 2023 (SLD2023) di Singapura.</p>\n<p>Kementerian Pertahanan dalam kenyataan memaklumkan, perkara itu selaras dengan tonggak ketiga strategi pertahanan negara yang menekankan perkongsian berwibawa seperti digariskan dalam Kertas Putih Pertahanan.</p>\n<p>Kenyataan itu memaklumkan, forum dari 2 hingga 4 Jun itu memberi impak besar kepada Malaysia sebagai peneraju dalam isu pertahanan dan keselamatan di Asia Tenggara untuk bertukar-tukar pandangan serta mendengar pendirian negara lain berhubung isu keselamatan terkini.</p>\n<p>"Di samping itu, forum berkenaan memperkukuh hubungan pertahanan dengan negara-negara berkepentingan," menurut kenyataan itu.</p>\n<p>SLD2023 ialah forum keselamatan bertaraf antarabangsa melibatkan penyertaan menteri-menteri pertahanan dan pegawai-pegawai tinggi kerajaan dari negara di rantau Asia Pasifik dan benua Eropah.</p>\n<p>Semasa forum tiga hari itu, Mohamad turut mengadakan pertemuan dua hala dan pelbagai hala bersama rakan sejawat dari negara strategik, antaranya Singapura, Portugal, China serta Filipina.</p>\n<p>Selain itu, beliau menghadiri sesi mesyuarat bersama menteri pertahanan negara anggota Perjanjian Pertahanan Lima Negara (FPDA). - BERNAMA</p>\n\n',
    word_count: 171,
  },
  {
    nid: 1110263,
    title: 'Ahmad Faizal tak bertanding',
    created: 1685885526,
    changed: 1685885728,
    sponsored: 0,
    premium: 0,
    url: 'https://www.bharian.com.my/berita/nasional/2023/06/1110263/ahmad-faizal-tak-bertanding',
    internal_url: '/berita/nasional/2023/06/1110263/ahmad-faizal-tak-bertanding',
    emotion: null,
    segment: null,
    sentiment: null,
    field_hide_related_articles: false,
    field_force_ads: [

    ],
    field_article_author: {
      tid: 1287,
      name: 'Mohd Amin Jalil',
      email: null,
      photo: null,
      internal_url: '/authors/mohd-amin-jalil',
    },
    field_author_email: 'bhnews@bh.com.my',
    field_article_authors: [
      {
        tid: 1287,
        name: 'Mohd Amin Jalil',
        email: null,
        photo: null,
        internal_url: '/authors/mohd-amin-jalil',
      },
    ],
    field_byline_prefix: 'Oleh',
    field_article_topic: {
      tid: 1,
      name: 'Nasional',
    },
    field_tags: [
      {
        tid: 1479,
        name: 'nasional',
      },
      {
        tid: 7331,
        name: 'bersatu',
      },
      {
        tid: 2188,
        name: 'prn',
      },
      {
        tid: 70412,
        name: 'Faizal Azumu',
      },
    ],
    field_article_images: [
      {
        fid: '4776290',
        uid: '9',
        filename: 'BH4TAKTANDING_1685885717.jpg',
        uri: 'gs://images/articles/BH4TAKTANDING_1685885717.jpg',
        filemime: 'image/jpeg',
        filesize: '127802',
        status: '1',
        timestamp: '1685885719',
        uuid: '376b3966-f6fd-4f69-87d3-1b4046b796ae',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '540',
        url: 'https://assets.bharian.com.my/images/articles/BH4TAKTANDING_1685885717.jpg',
        caption: 'Ahmad Faizal (tengah), Rais dan Eddin Syazlee pada sidang media - Foto NSTP/Mohd Amin Jalil',
        gn4id: 'bh-43657418',
      },
    ],
    field_article_images_filtered: [
      {
        fid: '4776290',
        uid: '9',
        filename: 'BH4TAKTANDING_1685885717.jpg',
        uri: 'gs://images/articles/BH4TAKTANDING_1685885717.jpg',
        filemime: 'image/jpeg',
        filesize: '127802',
        status: '1',
        timestamp: '1685885719',
        uuid: '376b3966-f6fd-4f69-87d3-1b4046b796ae',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '540',
        url: 'https://assets.bharian.com.my/images/articles/BH4TAKTANDING_1685885717.jpg',
        caption: 'Ahmad Faizal (tengah), Rais dan Eddin Syazlee pada sidang media - Foto NSTP/Mohd Amin Jalil',
        gn4id: 'bh-43657418',
      },
    ],
    field_article_videos: null,
    field_image_listing_featured_v2: 'https://assets.bharian.com.my/images/articles/BH4TAKTANDING-O_BHfield_image_listing_featured_v2.var_1685885728.jpg',
    field_image_listing_v2: 'https://assets.bharian.com.my/images/articles/BH4TAKTANDING-O_BHfield_image_listing_v2.var_1685885727.jpg',
    field_image_portrait: 'https://assets.bharian.com.my/images/articles/BH4TAKTANDING-O_BHfield_image_portrait.var_1685885727.jpg',
    field_image_socialmedia: 'https://assets.bharian.com.my/images/articles/BH4TAKTANDING-O_BHfield_image_socialmedia.var_1685885726.jpg',
    field_image_first_sb_featured: 'https://assets.bharian.com.my/images/articles/BH4TAKTANDING-O_BHfield_image_first_sb_featured.var_1685885725.jpg',
    field_image_second_sb_featured: 'https://assets.bharian.com.my/images/articles/BH4TAKTANDING-O_BHfield_image_second_sb_featured.var_1685885724.jpg',
    field_image_listing_featured: 'https://assets.bharian.com.my/images/articles/BH4TAKTANDING-O_BHfield_image_listing_featured.var_1685885724.jpg',
    field_image_listing_th: 'https://assets.bharian.com.my/images/articles/BH4TAKTANDING-O_BHfield_image_listing_th.var_1685885723.jpg',
    field_image_three_wide_col: 'https://assets.bharian.com.my/images/articles/BH4TAKTANDING-O_BHfield_image_three_wide_col.var_1685885722.jpg',
    field_image_two_wide_col: null,
    field_image_mobile_th: null,
    field_article_lead: 'SEREMBAN: Timbalan Presiden BERSATU, Datuk Seri Ahmad Faizal Azumu mengesahkan tidak akan bertanding mana-mana kerusi pada Pilihan Raya Negeri (PRN), di enam negeri akan datang.',
    body: 'bhnews@bh.com.my<p /><p>SEREMBAN: Timbalan Presiden BERSATU, Datuk Seri Ahmad Faizal Azumu mengesahkan tidak akan bertanding mana-mana kerusi pada Pilihan Raya Negeri (PRN), di enam negeri akan datang.</p><p>Beliau berkata, walaupun baharu mengambil alih sebagai Pengerusi Badan Pimpinan Negeri (BPN) Perikatan Nasional (PN) dan Pengerusi BERSATU Negeri Sembilan, ia sekadar untuk persiapan dan membantu jentera parti bagi menghadapi PRN.</p><p>"Walaupun saya telah dilantik ke jawatan ini (Pengerusi BPN dan Pengerusi BERSATU Negeri Sembilan), ia hanya untuk melicinkan jentera pilihan raya.</p><p>"Saya tidak akan bertanding di mana-mana kerusi di enam negeri pada pilihan raya negeri termasuk di Negeri Sembilan.</p><p>"Saya berasal dari Perak tapi sebagai anggota parti, saya perlu akur arahan kepemimpinan tertinggi, jadi tugas saya hanyalah untuk memperhambakan diri dan menguatkan jentera parti bagi menghadapi pilihan raya," katanya.</p><p>Beliau ditemu pemberita selepas mempengerusikan mesyuarat Badan Pimpinan BERSATU Negeri Sembilan, di sini, hari ini.</p><p>Yang turut hadir, Penasihat BERSATU Negeri Sembilan, Tan Sri Dr Rais Yatim dan Ketua BERSATU Bahagian Kuala Pilah yang juga bekas BPN PN negeri, Datuk Eddin Syazlee Sith.</p><p>Mengulas lanjut, Ahmad Faizal yang juga Pengerusi BPN PN Perak, menegaskan bahawa PN dan BERSATU Negeri Sembilan tidak menghadapi sebarang masalah dari segi kepemimpinan sebelum ini susulan pelantikan berkenaan.</p><p>Mengulas mengenai pembahagian kerusi dan calon PRN, beliau yang juga Pengerusi Jawatankuasa Pembahagian Kerusi BERSATU Pusat, berkata perkara berkenaan berjalan lancar dan kini sedang berada di peringkat saringan membabitkan calon-calon yang </p><p>akan mewakili parti.</p><p /><p /><p>© New Straits Times Press (M) Bhd</p>',
    body_with_inline: '</p><p>SEREMBAN: Timbalan Presiden BERSATU, Datuk Seri Ahmad Faizal Azumu mengesahkan tidak akan bertanding mana-mana kerusi pada Pilihan Raya Negeri (PRN), di enam negeri akan datang.</p>\n<p>Beliau berkata, walaupun baharu mengambil alih sebagai Pengerusi Badan Pimpinan Negeri (BPN) Perikatan Nasional (PN) dan Pengerusi BERSATU Negeri Sembilan, ia sekadar untuk persiapan dan membantu jentera parti bagi menghadapi PRN.</p>\n<p>"Walaupun saya telah dilantik ke jawatan ini (Pengerusi BPN dan Pengerusi BERSATU Negeri Sembilan), ia hanya untuk melicinkan jentera pilihan raya.</p>\n<p>"Saya tidak akan bertanding di mana-mana kerusi di enam negeri pada pilihan raya negeri termasuk di Negeri Sembilan.</p>\n<p>"Saya berasal dari Perak tapi sebagai anggota parti, saya perlu akur arahan kepemimpinan tertinggi, jadi tugas saya hanyalah untuk memperhambakan diri dan menguatkan jentera parti bagi menghadapi pilihan raya," katanya.</p>\n<p>Beliau ditemu pemberita selepas mempengerusikan mesyuarat Badan Pimpinan BERSATU Negeri Sembilan, di sini, hari ini.</p>\n<p>Yang turut hadir, Penasihat BERSATU Negeri Sembilan, Tan Sri Dr Rais Yatim dan Ketua BERSATU Bahagian Kuala Pilah yang juga bekas BPN PN negeri, Datuk Eddin Syazlee Sith.</p>\n<p>Mengulas lanjut, Ahmad Faizal yang juga Pengerusi BPN PN Perak, menegaskan bahawa PN dan BERSATU Negeri Sembilan tidak menghadapi sebarang masalah dari segi kepemimpinan sebelum ini susulan pelantikan berkenaan.</p>\n<p>Mengulas mengenai pembahagian kerusi dan calon PRN, beliau yang juga Pengerusi Jawatankuasa Pembahagian Kerusi BERSATU Pusat, berkata perkara berkenaan berjalan lancar dan kini sedang berada di peringkat saringan membabitkan calon-calon yang </p>\n<p>akan mewakili parti.</p>\n',
    word_count: 234,
  },
  {
    nid: 1110261,
    title: 'Jangan jadikan isu agama polemik, perbalahan politik',
    created: 1685884861,
    changed: 1685884861,
    sponsored: 0,
    premium: 0,
    url: 'https://www.bharian.com.my/berita/nasional/2023/06/1110261/jangan-jadikan-isu-agama-polemik-perbalahan-politik',
    internal_url: '/berita/nasional/2023/06/1110261/jangan-jadikan-isu-agama-polemik-perbalahan-politik',
    emotion: null,
    segment: null,
    sentiment: null,
    field_hide_related_articles: false,
    field_force_ads: [

    ],
    field_article_author: {
      tid: 136,
      name: 'Suzalina Halid',
      email: null,
      photo: null,
      internal_url: '/authors/suzalina-halid',
    },
    field_author_email: 'suzalina@bh.com.my',
    field_article_authors: [
      {
        tid: 136,
        name: 'Suzalina Halid',
        email: null,
        photo: null,
        internal_url: '/authors/suzalina-halid',
      },
    ],
    field_byline_prefix: 'Oleh',
    field_article_topic: {
      tid: 1,
      name: 'Nasional',
    },
    field_tags: [
      {
        tid: 1479,
        name: 'nasional',
      },
      {
        tid: 23057,
        name: 'Yang di-pertuan agong',
      },
      {
        tid: 26662,
        name: 'hari keputeraan',
      },
      {
        tid: 341917,
        name: 'ucapan agong',
      },
    ],
    field_article_images: [
      {
        fid: '4776268',
        uid: '9',
        filename: 'Agong_1685884851.jpg',
        uri: 'gs://images/articles/Agong_1685884851.jpg',
        filemime: 'image/jpeg',
        filesize: '327031',
        status: '1',
        timestamp: '1685884852',
        uuid: '19b94893-c3e6-48c2-bb9b-a0b903ee3096',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '640',
        url: 'https://assets.bharian.com.my/images/articles/Agong_1685884851.jpg',
        caption: '',
        gn4id: 'bh-33786932',
      },
    ],
    field_article_images_filtered: [
      {
        fid: '4776268',
        uid: '9',
        filename: 'Agong_1685884851.jpg',
        uri: 'gs://images/articles/Agong_1685884851.jpg',
        filemime: 'image/jpeg',
        filesize: '327031',
        status: '1',
        timestamp: '1685884852',
        uuid: '19b94893-c3e6-48c2-bb9b-a0b903ee3096',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '640',
        url: 'https://assets.bharian.com.my/images/articles/Agong_1685884851.jpg',
        caption: '',
        gn4id: 'bh-33786932',
      },
    ],
    field_article_videos: null,
    field_image_listing_featured_v2: 'https://assets.bharian.com.my/images/articles/BH4AGONG-O_BHfield_image_listing_featured_v2.var_1685884860.jpg',
    field_image_listing_v2: 'https://assets.bharian.com.my/images/articles/BH4AGONG-O_BHfield_image_listing_v2.var_1685884860.jpg',
    field_image_portrait: 'https://assets.bharian.com.my/images/articles/BH4AGONG-O_BHfield_image_portrait.var_1685884859.jpg',
    field_image_socialmedia: 'https://assets.bharian.com.my/images/articles/BH4AGONG-O_BHfield_image_socialmedia.var_1685884858.jpg',
    field_image_first_sb_featured: 'https://assets.bharian.com.my/images/articles/BH4AGONG-O_BHfield_image_first_sb_featured.var_1685884857.jpg',
    field_image_second_sb_featured: 'https://assets.bharian.com.my/images/articles/BH4AGONG-O_BHfield_image_second_sb_featured.var_1685884856.jpg',
    field_image_listing_featured: 'https://assets.bharian.com.my/images/articles/BH4AGONG-O_BHfield_image_listing_featured.var_1685884855.jpg',
    field_image_listing_th: 'https://assets.bharian.com.my/images/articles/BH4AGONG-O_BHfield_image_listing_th.var_1685884854.jpg',
    field_image_three_wide_col: 'https://assets.bharian.com.my/images/articles/BH4AGONG-O_BHfield_image_three_wide_col.var_1685884854.jpg',
    field_image_two_wide_col: null,
    field_image_mobile_th: null,
    field_article_lead: "Kuala Lumpur: Al-Sultan Abdullah Ri'ayatuddin Al-Mustafa Billah Shah mengingatkan seluruh rakyat negara ini agar tidak menjadikan isu agama sebagai polemik dan perbalahan politik.",
    body: "suzalina@bh.com.my <p /><p>Kuala Lumpur: Al-Sultan Abdullah Ri'ayatuddin Al-Mustafa Billah Shah mengingatkan seluruh rakyat negara ini agar tidak menjadikan isu agama sebagai polemik dan perbalahan politik.</p><p>  Dalam titah sempena Hari Keputeraan Rasmi Yang di-Pertuan Agong malam ini, Seri Paduka turut mengajak semua pihak membuang agenda retorik perpecahan dengan bersatu hati untuk mengemudi negara ke arah pembentukan masa hadapan lebih baik.</p><p> Al-Sultan Abdullah juga mengingatkan, semua pihak perlu menghormati kedudukan agama Islam sebagai agama Persekutuan seperti diperuntukkan dalam Perkara 3 Perlembagaan Persekutuan.</p><p>Titah baginda lagi, kedudukan Raja-Raja Melayu sebagai Ketua Agama Islam juga perlu dihormati, namun agama-agama lain masih boleh diamalkan dengan aman dan damai.</p><p>\"Semangat penuh toleransi rakyat Malaysia dalam kemajmukan yang ada, sebenarnya adalah asas kekuatan utama negara. </p><p>\"Justeru, bagi membina sebuah negara yang gagah perkasa, maju jaya, berwibawa dan bermaruah, kita semua hendaklah membuang agenda retorik perpecahan dan sebaliknya bersatu hati untuk mengemudi negara ke arah pembentukan masa hadapan lebih baik,\" titah Seri Paduka sempena sambutan Ulang Tahun Hari Keputeraan Rasmi Baginda yang disiarkan melalui televisyen tempatan malam ini.</p><p>Ini tahun kelima Al-Sultan Abdullah dan Raja Permaisuri Agong, Tunku Azizah Aminah Maimunah Iskandariah meraikan Hari Keputeraan Rasmi Yang di-Pertuan Agong bersama rakyat Malaysia.</p><p>Mahu amalan demokrasi di negara ini terus menjadi asas kestabilan dan keharmonian negara, Seri Paduka bertitah, Pilihan Raya Umum ke-15 (PRU15) tahun lalu dan proses pembentukan Kerajaan Persekutuan yang lancar, dalam suasana aman dan damai menjadi bukti bahawa amalan demokrasi sejak tujuh dekad lalu, masih kekal subur di negara ini.</p><p>\"Beta berasa amat bersyukur kerana hari keputeraan rasmi beta pada tahun ini disambut dalam suasana landskap negara yang stabil dan sentosa. </p><p>\"Beta ingin mengajak barisan kepemimpinan negara untuk terus berkhidmat setulus hati dan meningkatkan usaha membentuk sistem pentadbiran negara yang cekap, mesra rakyat dan berintegriti demi membela masa hadapan rakyat beta dan negara bertuah ini,\" titah baginda.</p><p>Yang di-Pertuan Agong melihat Malaysia mempunyai potensi sangat besar untuk menjadi sebuah negara maju dan disegani kerana dilimpahi nikmat keamanan, kepelbagaian sumber dan modal insan berkualiti serta mempunyai semangat juang yang tinggi.</p><p>\"Sebenarnya kekuatan utama negara ini adalah rakyatnya. Rakyat Malaysia yang amat mencintai kedamaian, keharmonian dan kesatuan dalam kehidupan seharian serta menerima kemajmukan yang wujud dengan penuh toleran.</p><p>\"Rakyat Malaysia juga sekian lama berjaya mencipta nama di persada dunia dalam pelbagai bidang, termasuk dalam mencorak landskap geopolitik serantau dan global,\" titah Seri Paduka lagi.</p><p>Baginda turut melahirkan penghargaan buat semua rakyat, merangkumi kerajaan, anggota pentadbiran, penjawat awam dan pasukan keselamatan yang menyumbang kepada kesejahteraan dan keamanan negara. </p><p>Seri Paduka menzahirkan ucapan setinggi-tinggi terima kasih kepada rakyat atas ucapan tahniah dan doa dipersembahkan sempena hari keputeraan rasmi hari ini, yang menambah iltizam dan tekad baginda untuk terus memayungi rakyat dengan penuh keadilan dan kesaksamaan.</p><p>\"Marilah sama-sama kita berdoa semoga rakyat Malaysia dan negara yang kita cintai ini akan terus kekal aman dan makmur, sentiasa berada di bawah lindungan Allah SWT serta dijauhi daripada musibah dan bala bencana,\" titah baginda.</p><p>© New Straits Times Press (M) Bhd</p>",
    body_with_inline: "</p><p>Kuala Lumpur: Al-Sultan Abdullah Ri'ayatuddin Al-Mustafa Billah Shah mengingatkan seluruh rakyat negara ini agar tidak menjadikan isu agama sebagai polemik dan perbalahan politik.</p>\n<p>  Dalam titah sempena Hari Keputeraan Rasmi Yang di-Pertuan Agong malam ini, Seri Paduka turut mengajak semua pihak membuang agenda retorik perpecahan dengan bersatu hati untuk mengemudi negara ke arah pembentukan masa hadapan lebih baik.</p>\n<p> Al-Sultan Abdullah juga mengingatkan, semua pihak perlu menghormati kedudukan agama Islam sebagai agama Persekutuan seperti diperuntukkan dalam Perkara 3 Perlembagaan Persekutuan.</p>\n<p>Titah baginda lagi, kedudukan Raja-Raja Melayu sebagai Ketua Agama Islam juga perlu dihormati, namun agama-agama lain masih boleh diamalkan dengan aman dan damai.</p>\n<p>\"Semangat penuh toleransi rakyat Malaysia dalam kemajmukan yang ada, sebenarnya adalah asas kekuatan utama negara. </p>\n<p>\"Justeru, bagi membina sebuah negara yang gagah perkasa, maju jaya, berwibawa dan bermaruah, kita semua hendaklah membuang agenda retorik perpecahan dan sebaliknya bersatu hati untuk mengemudi negara ke arah pembentukan masa hadapan lebih baik,\" titah Seri Paduka sempena sambutan Ulang Tahun Hari Keputeraan Rasmi Baginda yang disiarkan melalui televisyen tempatan malam ini.</p>\n<p>Ini tahun kelima Al-Sultan Abdullah dan Raja Permaisuri Agong, Tunku Azizah Aminah Maimunah Iskandariah meraikan Hari Keputeraan Rasmi Yang di-Pertuan Agong bersama rakyat Malaysia.</p>\n<p>Mahu amalan demokrasi di negara ini terus menjadi asas kestabilan dan keharmonian negara, Seri Paduka bertitah, Pilihan Raya Umum ke-15 (PRU15) tahun lalu dan proses pembentukan Kerajaan Persekutuan yang lancar, dalam suasana aman dan damai menjadi bukti bahawa amalan demokrasi sejak tujuh dekad lalu, masih kekal subur di negara ini.</p>\n<p>\"Beta berasa amat bersyukur kerana hari keputeraan rasmi beta pada tahun ini disambut dalam suasana landskap negara yang stabil dan sentosa. </p>\n<p>\"Beta ingin mengajak barisan kepemimpinan negara untuk terus berkhidmat setulus hati dan meningkatkan usaha membentuk sistem pentadbiran negara yang cekap, mesra rakyat dan berintegriti demi membela masa hadapan rakyat beta dan negara bertuah ini,\" titah baginda.</p>\n<p>Yang di-Pertuan Agong melihat Malaysia mempunyai potensi sangat besar untuk menjadi sebuah negara maju dan disegani kerana dilimpahi nikmat keamanan, kepelbagaian sumber dan modal insan berkualiti serta mempunyai semangat juang yang tinggi.</p>\n<p>\"Sebenarnya kekuatan utama negara ini adalah rakyatnya. Rakyat Malaysia yang amat mencintai kedamaian, keharmonian dan kesatuan dalam kehidupan seharian serta menerima kemajmukan yang wujud dengan penuh toleran.</p>\n<p>\"Rakyat Malaysia juga sekian lama berjaya mencipta nama di persada dunia dalam pelbagai bidang, termasuk dalam mencorak landskap geopolitik serantau dan global,\" titah Seri Paduka lagi.</p>\n<p>Baginda turut melahirkan penghargaan buat semua rakyat, merangkumi kerajaan, anggota pentadbiran, penjawat awam dan pasukan keselamatan yang menyumbang kepada kesejahteraan dan keamanan negara. </p>\n<p>Seri Paduka menzahirkan ucapan setinggi-tinggi terima kasih kepada rakyat atas ucapan tahniah dan doa dipersembahkan sempena hari keputeraan rasmi hari ini, yang menambah iltizam dan tekad baginda untuk terus memayungi rakyat dengan penuh keadilan dan kesaksamaan.</p>\n<p>\"Marilah sama-sama kita berdoa semoga rakyat Malaysia dan negara yang kita cintai ini akan terus kekal aman dan makmur, sentiasa berada di bawah lindungan Allah SWT serta dijauhi daripada musibah dan bala bencana,\" titah baginda.</p>\n",
    word_count: 481,
  },
  {
    nid: 1110256,
    title: 'Nahas kereta api India: Siasatan tumpu sistem pengurusan trek elektronik',
    created: 1685884503,
    changed: 1685884503,
    sponsored: 0,
    premium: 0,
    url: 'https://www.bharian.com.my/dunia/asia/2023/06/1110256/nahas-kereta-api-india-siasatan-tumpu-sistem-pengurusan-trek-elektronik',
    internal_url: '/dunia/asia/2023/06/1110256/nahas-kereta-api-india-siasatan-tumpu-sistem-pengurusan-trek-elektronik',
    emotion: null,
    segment: null,
    sentiment: null,
    field_hide_related_articles: false,
    field_force_ads: [

    ],
    field_article_author: null,
    field_author_email: null,
    field_article_authors: [

    ],
    field_byline_prefix: null,
    field_article_topic: {
      tid: 8460,
      name: 'Asia',
    },
    field_tags: null,
    field_article_images: [
      {
        fid: '4776221',
        uid: '9',
        filename: 'BHNIDA_1685884491.jpg',
        uri: 'gs://images/articles/BHNIDA_1685884491.jpg',
        filemime: 'image/jpeg',
        filesize: '324277',
        status: '1',
        timestamp: '1685884492',
        uuid: '7e3fccba-4832-4122-a4ac-7cb0ad888e67',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '640',
        url: 'https://assets.bharian.com.my/images/articles/BHNIDA_1685884491.jpg',
        caption: 'Gerabak kereta api dialihkan menggunakan jentera berat dari landasan di tapak nahas di Balasore, negeri timur Odisha, India. - REUTERS',
        gn4id: 'bh-43657126',
      },
      {
        fid: '4776222',
        uid: '9',
        filename: 'bh9nagh_1685884494.jpg',
        uri: 'gs://images/articles/bh9nagh_1685884494.jpg',
        filemime: 'image/jpeg',
        filesize: '252284',
        status: '1',
        timestamp: '1685884494',
        uuid: 'a9e23dac-adcd-4d60-9112-461457332d90',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '640',
        url: 'https://assets.bharian.com.my/images/articles/bh9nagh_1685884494.jpg',
        caption: 'Pemandangan menunjukkan gerabak yang rosak di tapak di Balasore, negeri timur Odisha, India. - REUTERS',
        gn4id: 'bh-43657147',
      },
    ],
    field_article_images_filtered: [
      {
        fid: '4776221',
        uid: '9',
        filename: 'BHNIDA_1685884491.jpg',
        uri: 'gs://images/articles/BHNIDA_1685884491.jpg',
        filemime: 'image/jpeg',
        filesize: '324277',
        status: '1',
        timestamp: '1685884492',
        uuid: '7e3fccba-4832-4122-a4ac-7cb0ad888e67',
        rdf_mapping: [

        ],
        alt: '',
        title: '',
        width: '960',
        height: '640',
        url: 'https://assets.bharian.com.my/images/articles/BHNIDA_1685884491.jpg',
        caption: 'Gerabak kereta api dialihkan menggunakan jentera berat dari landasan di tapak nahas di Balasore, negeri timur Odisha, India. - REUTERS',
        gn4id: 'bh-43657126',
      },
    ],
    field_article_videos: null,
    field_image_listing_featured_v2: 'https://assets.bharian.com.my/images/articles/BHINDIA_BHfield_image_listing_featured_v2.var_1685884501.jpg',
    field_image_listing_v2: 'https://assets.bharian.com.my/images/articles/BHINDIA_BHfield_image_listing_v2.var_1685884500.jpg',
    field_image_portrait: 'https://assets.bharian.com.my/images/articles/BHINDIA_BHfield_image_portrait.var_1685884500.jpg',
    field_image_socialmedia: 'https://assets.bharian.com.my/images/articles/BHINDIA_BHfield_image_socialmedia.var_1685884499.jpg',
    field_image_first_sb_featured: 'https://assets.bharian.com.my/images/articles/BHINDIA_BHfield_image_first_sb_featured.var_1685884498.jpg',
    field_image_second_sb_featured: 'https://assets.bharian.com.my/images/articles/BHINDIA_BHfield_image_second_sb_featured.var_1685884497.jpg',
    field_image_listing_featured: 'https://assets.bharian.com.my/images/articles/BHINDIA_BHfield_image_listing_featured.var_1685884497.jpg',
    field_image_listing_th: 'https://assets.bharian.com.my/images/articles/BHINDIA_BHfield_image_listing_th.var_1685884496.jpg',
    field_image_three_wide_col: 'https://assets.bharian.com.my/images/articles/BHINDIA_BHfield_image_three_wide_col.var_1685884495.jpg',
    field_image_two_wide_col: null,
    field_image_mobile_th: null,
    field_article_lead: 'NEW DELHI: Pihak berkuasa menyiasat sistem pengurusan trek elektronik yang disyaki mereka tidak berfungsi dan menyebabkan nahas kereta api paling membawa maut di India dalam tempoh lebih dua dekad, kata pegawai kereta api hari ini.',
    body: "<p>NEW DELHI: Pihak berkuasa menyiasat sistem pengurusan trek elektronik yang disyaki mereka tidak berfungsi dan menyebabkan nahas kereta api paling membawa maut di India dalam tempoh lebih dua dekad, kata pegawai kereta api hari ini.</p><p>  Sekurang-kurangnya 275 orang terbunuh dalam nahas pada Jumaat itu apabila sebuah kereta api penumpang melanggar kereta api barang yang tidak bergerak, tersasar dari landasan dan melanggar sebuah lagi kereta api penumpang yang melalui arah bertentangan di negeri timur Odisha.</p><p>  Dalam taklimat terperinci pertama mereka mengenai nahas itu, pegawai Indian Railways berkata, kegagalan sistem pengurusan landasan menjadi fokus utama dalam penyiasatan.</p><p>  Pengarah Eksekutif Utama Indian Railways, Sandeep Mathur, berkata sistem pengurusan trek dikawal komputer yang dipanggil 'sistem interlock' yang mana ia mengarahkan kereta api ke landasan kosong pada titik di mana dua landasan bertemu.</p><p>  Katanya, ia juga menyelaras dan mengawal isyarat kepada tren yang akan datang, menunjukkan sama ada tren itu perlu bergerak lurus atau beralih ke landasan baharu.</p><p>  Ahli Lembaga Keretapi, Jaya Varma Sinha pula berkata sistem itu sepatutnya bebas gangguan dan bebas ralat. </p><p>  \"Ia dipanggil sistem bebas-gagal...walaupun ia gagal berfungsi, isyarat akan bertukar merah dan kereta api akan dihentikan.</p><p>  \"Bagaimanapun seperti disyaki, terdapat beberapa jenis masalah dalam sistem,\" katanya.</p><p>  Mengulas urutan kejadian yang membawa kepada nahas di stesen Bahanaga di daerah Balasore, Sinha berkata, Ekspres Coromandel menuju Chennai dari Kolkata bergerak keluar dari trek utama, memasuki trek gelung - trek sisi yang digunakan untuk meletakkan kereta api - dengan kelajuan 128 kph (80 mph) dan merempuh kereta api barang yang membawa bijih besi yang diletakkan di landasan gelung.</p><p /><p> </p><p /><p>  Nahas itu menyebabkan enjin dan empat atau lima koc pertama Coromandel Express melompat landasan, tumbang dan melanggar dua koc terakhir tren Yeshwantpur-Howrah menuju arah bertentangan di landasan utama kedua.</p><p>  Sistem saling kunci tidak sepatutnya membenarkan Coromandel Express mengambil trek gelung, kata Sinha.</p><p>  Katanya, beliau sudah bercakap dengan pemandu kereta api itu yang cedera dan diberitahu kereta api terbabit dalam had laju dan tidak melompat isyarat, yang mana semua ini akan disahkan oleh sistem yang merekodkan butiran trek dan kereta api.</p><p>  Sinha bagaimanapun tidak menamakan pemandu itu.</p><p>  Beliau mengakui terdapat banyak kemungkinan mengenai keadaan yang menimbulkan masalah.</p><p>  Ini mungkin termasuk ada seseorang menggali di kawasan kabel sistem elektronik dan merosakkannya, atau mungkin litar pintas atau kegagalan mesin.</p><p>  \"99.9 peratus tidak ada kemungkinan mesin itu gagal, tetapi terdapat 0.1 peratus kemungkinan kegagalan,\" katanya mengakui kemungkinan itu sentiasa ada dalam semua jenis sistem.</p><p /><p>© New Straits Times Press (M) Bhd</p>",
    body_with_inline: "<p>NEW DELHI: Pihak berkuasa menyiasat sistem pengurusan trek elektronik yang disyaki mereka tidak berfungsi dan menyebabkan nahas kereta api paling membawa maut di India dalam tempoh lebih dua dekad, kata pegawai kereta api hari ini.</p>\n<p>  Sekurang-kurangnya 275 orang terbunuh dalam nahas pada Jumaat itu apabila sebuah kereta api penumpang melanggar kereta api barang yang tidak bergerak, tersasar dari landasan dan melanggar sebuah lagi kereta api penumpang yang melalui arah bertentangan di negeri timur Odisha.</p>\n<p>  Dalam taklimat terperinci pertama mereka mengenai nahas itu, pegawai Indian Railways berkata, kegagalan sistem pengurusan landasan menjadi fokus utama dalam penyiasatan.</p>\n<p>  Pengarah Eksekutif Utama Indian Railways, Sandeep Mathur, berkata sistem pengurusan trek dikawal komputer yang dipanggil 'sistem interlock' yang mana ia mengarahkan kereta api ke landasan kosong pada titik di mana dua landasan bertemu.</p>\n<p>  Katanya, ia juga menyelaras dan mengawal isyarat kepada tren yang akan datang, menunjukkan sama ada tren itu perlu bergerak lurus atau beralih ke landasan baharu.</p>\n<p>  Ahli Lembaga Keretapi, Jaya Varma Sinha pula berkata sistem itu sepatutnya bebas gangguan dan bebas ralat. </p>\n<p>  \"Ia dipanggil sistem bebas-gagal...walaupun ia gagal berfungsi, isyarat akan bertukar merah dan kereta api akan dihentikan.</p>\n<p>  \"Bagaimanapun seperti disyaki, terdapat beberapa jenis masalah dalam sistem,\" katanya.</p>\n<p>  Mengulas urutan kejadian yang membawa kepada nahas di stesen Bahanaga di daerah Balasore, Sinha berkata, Ekspres Coromandel menuju Chennai dari Kolkata bergerak keluar dari trek utama, memasuki trek gelung - trek sisi yang digunakan untuk meletakkan kereta api - dengan kelajuan 128 kph (80 mph) dan merempuh kereta api barang yang membawa bijih besi yang diletakkan di landasan gelung.</p>\n<p> <figure class=\"article-image-item gn4-inline-image inline-image image-single-single\"><img class=\"img-responsive img-fluid lazyload\" typeof=\"foaf:Image\" data-src=\"https://assets.bharian.com.my/images/articles/bh9nagh_1685884494.jpg\" alt=\"Pemandangan menunjukkan gerabak yang rosak di tapak di Balasore, negeri timur Odisha, India. - REUTERS\" /><figcaption class=\"gn4-inline-image-caption\">Pemandangan menunjukkan gerabak yang rosak di tapak di Balasore, negeri timur Odisha, India. - REUTERS</figcaption></figure></p>\n<p>  Nahas itu menyebabkan enjin dan empat atau lima koc pertama Coromandel Express melompat landasan, tumbang dan melanggar dua koc terakhir tren Yeshwantpur-Howrah menuju arah bertentangan di landasan utama kedua.</p>\n<p>  Sistem saling kunci tidak sepatutnya membenarkan Coromandel Express mengambil trek gelung, kata Sinha.</p>\n<p>  Katanya, beliau sudah bercakap dengan pemandu kereta api itu yang cedera dan diberitahu kereta api terbabit dalam had laju dan tidak melompat isyarat, yang mana semua ini akan disahkan oleh sistem yang merekodkan butiran trek dan kereta api.</p>\n<p>  Sinha bagaimanapun tidak menamakan pemandu itu.</p>\n<p>  Beliau mengakui terdapat banyak kemungkinan mengenai keadaan yang menimbulkan masalah.</p>\n<p>  Ini mungkin termasuk ada seseorang menggali di kawasan kabel sistem elektronik dan merosakkannya, atau mungkin litar pintas atau kegagalan mesin.</p>\n<p>  \"99.9 peratus tidak ada kemungkinan mesin itu gagal, tetapi terdapat 0.1 peratus kemungkinan kegagalan,\" katanya mengakui kemungkinan itu sentiasa ada dalam semua jenis sistem.</p>\n",
    word_count: 392,
  },
];
