export = [
  {
    title: 'Netizens Applaud E-Hailing Driver For Cancelling Ride After 6 Students Barge Into His Car',
    link: 'https://says.com/my/news/netizens-applaud-e-hailing-driver-for-cancelling-ride-after-6-students-barge-into-his-car',
    imageUrl: 'https://images.says.com/uploads/story/cover_image/62903/thumb_b83c.png',
    date: '2023-06-02T17:28:37+08:00',
    author: 'Parvinsivam Thirunamakarasu',
  },
  {
    title: "M'sian Finds 3CM Rusty Wire In Takoyaki Ball While Eating With Her 2-Year-Old Toddler",
    link: 'https://says.com/my/news/rusty-wire-takoyaki-2-year-old-toddler',
    imageUrl: 'https://images.says.com/uploads/story/cover_image/62889/thumb_8ee8.jpg',
    date: '2023-06-02T13:04:18+08:00',
    author: 'Yap Wan Xiang',
  },
  {
    title: "[VIDEO] Nepali Sherpa Saves M'sian Climber By Carrying Him Down Mt Everest For 6 Hours",
    link: 'https://says.com/my/news/gelje-sherpa-saves-malaysian-climber-carrying-him-on-back-hours-everest',
    imageUrl: 'https://images.says.com/uploads/story/cover_image/62897/thumb_8dbd.jpg',
    date: '2023-06-02T16:31:05+08:00',
    author: 'Sadho Ram',
  },
  {
    title: "\"Worse Than A Robbery\" — Immigration Officers Break Down Elderly KL Couple's Door At 3AM",
    link: 'https://says.com/my/news/immigration-officers-break-down-couple-s-door-at-3am-in-kl',
    imageUrl: 'https://images.says.com/uploads/story/cover_image/62890/thumb_3cf0.jpg',
    date: '2023-06-02T12:37:41+08:00',
    author: 'Sadho Ram',
  },
  {
    title: "Netizens Praise Security Guard Who Clamped Traffic Cop's Motorcycle In OKU Parking Spot",
    link: 'https://says.com/my/news/netizens-praise-security-guard-who-clamped-traffic-cop-s-motorcycle-in-oku-parking-spot',
    imageUrl: 'https://images.says.com/uploads/story/cover_image/62883/thumb_e5b0.png',
    date: '2023-06-02T11:54:44+08:00',
    author: 'Parvinsivam Thirunamakarasu',
  },
  {
    title: 'Viral TikTok Hack For Cooking Poached Egg Leaves Mum With Burns On Her Face',
    link: 'https://says.com/my/news/tiktok-microwave-cooking-poached-egg-hack-leaves-mum-with-burn',
    imageUrl: 'https://images.says.com/uploads/story/cover_image/62870/thumb_9a7b.jpg',
    date: '2023-06-01T17:44:35+08:00',
    author: 'Sadho Ram',
  },
  {
    title: '"Is It Not Enough?" — Husband Asks How Wife Spent RM200 He Provided For Household Expenses',
    link: 'https://says.com/my/news/husband-asks-wife-where-she-spent-rm200-for-household-expenses',
    imageUrl: 'https://images.says.com/uploads/story/cover_image/62876/thumb_9af5.jpg',
    date: '2023-06-01T17:29:17+08:00',
    author: 'May Vin Ang',
  },
  {
    title: '[VIDEO] PJ Company Puts Up Job Ad Hiring TikTok Dancers For RM10,000 A Month',
    link: 'https://says.com/my/news/pj-company-job-ad-tiktok-dancers-rm10k-monthly',
    imageUrl: 'https://images.says.com/uploads/story/cover_image/62854/thumb_694d.png',
    date: '2023-06-01T11:43:01+08:00',
    author: 'Aqasha Nur’aiman',
  },
  {
    title: '"We Found Crocodile Organs" — Raid Unveils Illegal Wildlife Parts At Chow Kit Apothecary',
    link: 'https://says.com/my/news/we-found-crocodile-organs-raid-unveils-wildlife-body-parts-at-chow-kit-apothecary',
    imageUrl: 'https://images.says.com/uploads/story/cover_image/62852/thumb_4ed0.png',
    date: '2023-06-01T11:12:35+08:00',
    author: 'Parvinsivam Thirunamakarasu',
  },
  {
    title: "Migrant Employee Wins RM65,000 Grand Prize In SG Company's 'Squid Game'-Themed Event",
    link: 'https://says.com/my/news/indian-employee-wins-prize-in-sg-company-squid-game-themed-event',
    imageUrl: 'https://images.says.com/uploads/story/cover_image/62848/thumb_35e7.jpg',
    date: '2023-06-01T10:48:53+08:00',
    author: 'May Vin Ang',
  },
];
