export = [
  {
    title: '[VIDEO] Gara-Gara Lipas Masuk Kereta, Gadis Ini Tak Fikir Banyak Terus Lompat Ke Depan',
    link: 'https://says.com/my/seismik/gara-gara-lipas-masuk-kereta-gadis-ini-tak-fikir-banyak-terus-lompat-ke-depan',
    imageUrl: 'https://images.says.com/uploads/story/cover_image/62907/thumb_1eaa.jpeg',
    date: '2023-06-02T17:57:16+08:00',
    author: 'Dania Hamdan',
  },
  {
    title: 'Ini Tips Penjagaan Untuk Anda Yang Miliki Tumit Kaki Kasar. Confirm Licin Lepas Ini!',
    link: 'https://says.com/my/seismik/ini-tips-penjagaan-untuk-anda-yang-miliki-tumit-kaki-kasar-confirm-licin-lepas-ini',
    imageUrl: 'https://images.says.com/uploads/story/cover_image/62905/thumb_22c6.png',
    date: '2023-06-02T17:43:49+08:00',
    author: 'Ellina Chan',
  },
  {
    title: "Gelagat Sekumpulan Penonton Selamba Menari Zapin Dekat 'Showcase Indie' Ini Curi Tumpuan",
    link: 'https://says.com/my/seismik/gelagat-sekumpulan-penonton-selamba-menari-zapin-dekat-showcase-indie-ini-curi-tumpuan',
    imageUrl: 'https://images.says.com/uploads/story/cover_image/62906/thumb_9031.jpg',
    date: '2023-06-02T17:35:29+08:00',
    author: 'Aishah Shahirah ',
  },
  {
    title: "Sazzy Falak Kini Tampil Dalam Musim Terbaharu Program Bual Bicara 'Women Talk'",
    link: 'https://says.com/my/seismik/sazzy-falak-kini-tampil-dalam-musim-terbaharu-program-bual-bicara-women-talk',
    imageUrl: 'https://images.says.com/uploads/story/cover_image/62902/thumb_2c69.jpg',
    date: '2023-06-02T17:11:20+08:00',
    author: 'Aishah Shahirah ',
  },
  {
    title: "Tetap Berikan Makanan Pada Suami Walaupun Marah, Gelagat Isteri 'Muka Ketat' Ini Cuit Hati",
    link: 'https://says.com/my/seismik/tetap-berikan-makanan-pada-suami-walaupun-marah-gelagat-isteri-muka-ketat-ini-cuit-hati',
    imageUrl: 'https://images.says.com/uploads/story/cover_image/62895/thumb_b3de.jpg',
    date: '2023-06-02T16:31:44+08:00',
    author: 'Nany Rahman',
  },
  {
    title: 'Bangga Dapat Anugerah Dekan, Pemuda Ini Sempoi Pakai Selempang Pink Di Stesen Minyak',
    link: 'https://says.com/my/seismik/bangga-dapat-anugerah-dekan-pemuda-ini-sempoi-pakai-selempang-pink-di-stesen-minyak',
    imageUrl: 'https://images.says.com/uploads/story/cover_image/62904/thumb_609c.png',
    date: '2023-06-02T16:16:23+08:00',
    author: 'Dania Hamdan',
  },
  {
    title: '[VIDEO] Nampak Bayangan Tangan Main Dengan Anak, Sekali Sergah Sebenarnya Tiada Siapa',
    link: 'https://says.com/my/seismik/video-nampak-bayangan-tangan-main-dengan-anak-sekali-sergah-sebenarnya-tiada-siapa',
    imageUrl: 'https://images.says.com/uploads/story/cover_image/62899/thumb_2cc5.png',
    date: '2023-06-02T16:02:00+08:00',
    author: 'Ellina Chan',
  },
  {
    title: 'Gara-Gara Si Ibu Ada Hutang Ah Long, Kereta Milik Anak Ditarik Ini Buat Ramai Risau',
    link: 'https://says.com/my/seismik/gara-gara-si-ibu-ada-hutang-ah-long-kereta-milik-anak-ditarik-ini-buat-ramai-risau',
    imageUrl: 'https://images.says.com/uploads/story/cover_image/62896/thumb_d128.jpg',
    date: '2023-06-02T14:52:35+08:00',
    author: 'Aishah Shahirah ',
  },
  {
    title: '[VIDEO] Posing Dengan Gajah Siap Kena Angkat, Ramai Pula Yang Kesian Dekat Haiwan Ini',
    link: 'https://says.com/my/seismik/video-posing-dengan-gajah-siap-kena-angkat-ramai-pula-yang-kesian-dekat-haiwan-ini',
    imageUrl: 'https://images.says.com/uploads/story/cover_image/62898/thumb_f413.png',
    date: '2023-06-02T14:16:29+08:00',
    author: 'Dania Hamdan',
  },
];
